(async function () {
  'use strict';

  var tg = window.Telegram && window.Telegram.WebApp ? window.Telegram.WebApp : null;
  if (tg) { try { tg.ready(); tg.expand(); tg.setHeaderColor('#100806'); tg.setBackgroundColor('#0c0706'); } catch (_) {} }

  var LANGS = [
    ['ar','🇸🇦','العربية'],['en','🇬🇧','English'],['fr','🇫🇷','Français'],['de','🇩🇪','Deutsch'],
    ['it','🇮🇹','Italiano'],['es','🇪🇸','Español'],['pt','🇵🇹','Português'],['ru','🇷🇺','Русский'],
    ['zh-cn','🇨🇳','简体中文'],['zh-tw','🇹🇼','繁體中文'],['id','🇮🇩','Bahasa Indonesia'],['th','🇹🇭','ภาษาไทย'],
    ['tr','🇹🇷','Türkçe'],['ko','🇰🇷','한국어'],['ja','🇯🇵','日本語'],['vi','🇻🇳','Tiếng Việt']
  ];
  var LANGUAGE_CONFIRM_TEXT = {
    ar:'تأكيد اللغة',en:'Confirm language',fr:'Confirmer la langue',de:'Sprache bestätigen',
    it:'Conferma lingua',es:'Confirmar idioma',pt:'Confirmar idioma',ru:'Подтвердить язык',
    'zh-cn':'确认语言','zh-tw':'確認語言',id:'Konfirmasi bahasa',th:'ยืนยันภาษา',
    tr:'Dili onayla',ko:'언어 확인',ja:'言語を確定',vi:'Xác nhận ngôn ngữ'
  };
  var EN = {
    eyebrow:'CASTLE COMMAND',title:'Doomsday Command',subtitle:'Manage every castle from one control center.',telegram:'Telegram ID',search:'Search by nickname or castle ID',copy:'Copy settings',cancel:'Cancel',apply:'Apply settings',chooseSource:'Choose the source castle.',chooseTargets:'Select one or more target castles.',copied:'Settings copied to the selected castles.',noFarms:'No castles are linked to this Telegram account.',on:'ONLINE',off:'STOPPED',save:'Save all settings',saving:'Saving…',saved:'Settings sent to the bot.',openTelegram:'Open this page from the Telegram bot.',invalid:'Castle data is invalid. Reopen the page from the bot.',back:'Back',identity:'Castle identity',nickname:'Castle nickname',email:'IGG email',password:'New password',passwordHint:'Leave blank to keep the saved password',functions:'Automation functions',gather:'Resource gathering',food:'Food',wood:'Wood',steel:'Steel',oil:'Oil',total:'Total legions',maxFive:'The total cannot exceed 5 legions.',zombie:'Rebel / zombie settings',maxLevel:'Maximum level',minLevel:'Minimum level',multiplier:'Multiplier',auto:'Automatic: ×10, ×5, ×2, then normal',normal:'Normal',shops:'Stores',arenaStore:'Arena Store',vipStore:'VIP Store — resources only',shopSafety:'The bot buys only live selected items. Gems and paid attempt purchases are permanently blocked.',points:'points',vip:'VIP',qty:'Qty',language:'Language',source:'Source',targets:'Targets',selectTarget:'Select target castles first.',transfer:'Transfer resources',transferTarget:'Receiving castle ID',transferHint:'Select the farms below, then enter the amount each selected farm should send.',selectedFarms:'Selected farms',enterAmounts:'Amount from each farm',sendTransfer:'Send resources',confirmTransfer:'Confirm transfer',close:'Close',transferInvalid:'Enter a valid target ID, select at least one farm, and enter a resource amount.',transferSent:'Transfer request sent. The bot will send the detailed report in Telegram.',perFarm:'The same amounts apply to every selected farm.'
  };
  Object.assign(EN,{region:'Region',ordinaryResources:'Open ordinary resources',stockUpdated:'Last confirmed',stockUnavailable:'Waiting for the next bot connection',stockLimitNote:'Actual sending can be lower because of Trading Post limits, tax, and receiver limits.',castlesTab:'Castles',castleSettings:'Castle settings',protectedSection:'Protected',notAuthorized:'You are not authorized to use this feature.'});
  var OV = {
    ar:{eyebrow:'قيادة القلاع',title:'قيادة دومزداي',subtitle:'تحكم في كل قلاعك من لوحة واحدة.',telegram:'معرّف تيليجرام',search:'ابحث باسم القلعة أو المعرّف',copy:'نسخ الإعدادات',cancel:'إلغاء',apply:'تطبيق الإعدادات',chooseSource:'اختر القلعة المصدر.',chooseTargets:'علّم على قلعة أو أكثر لتطبيق الإعدادات.',copied:'تم نسخ الإعدادات إلى القلاع المحددة.',noFarms:'لا توجد قلاع مرتبطة بحساب تيليجرام.',on:'شغالة',off:'متوقفة',save:'حفظ كل الإعدادات',saving:'جاري الحفظ…',saved:'تم إرسال الإعدادات إلى البوت.',openTelegram:'افتح الصفحة من زر البوت داخل تيليجرام.',invalid:'بيانات القلاع غير صالحة. افتح الصفحة من البوت من جديد.',back:'رجوع',identity:'بيانات القلعة',nickname:'اسم مختصر للقلعة',email:'بريد IGG',password:'كلمة مرور جديدة',passwordHint:'اتركها فارغة للاحتفاظ بالمحفوظة',functions:'دوال التشغيل',gather:'جمع الموارد',food:'الطعام',wood:'الخشب',steel:'الفولاذ',oil:'البترول',total:'إجمالي الفيالق',maxFive:'الإجمالي لا يزيد عن 5 فيالق.',zombie:'إعدادات المتمردين / الزومبي',maxLevel:'أقصى مستوى',minLevel:'أدنى مستوى',multiplier:'المضاعف',auto:'تلقائي: ×10 ثم ×5 ثم ×2 ثم عادي',normal:'عادي',shops:'المتاجر',arenaStore:'متجر الحلبة',vipStore:'متجر VIP — بالموارد فقط',shopSafety:'الشراء من العناصر المختارة والمتاحة حاليًا فقط. الجواهر وشراء محاولات إضافية ممنوعان نهائيًا.',points:'نقطة',vip:'VIP',qty:'الكمية',language:'اللغة',source:'المصدر',targets:'الأهداف',selectTarget:'اختر قلاعًا مستهدفة أولًا.',transfer:'نقل الموارد',transferTarget:'معرف القلعة المستلمة',transferHint:'علّم على المزارع بالأسفل، ثم اكتب الكمية التي سترسلها كل مزرعة محددة.',selectedFarms:'المزارع المحددة',enterAmounts:'الكمية من كل مزرعة',sendTransfer:'إرسال الموارد',confirmTransfer:'تأكيد الإرسال',close:'إغلاق',transferInvalid:'اكتب معرفًا صحيحًا، وحدد مزرعة واحدة على الأقل، واكتب كمية مورد.',transferSent:'تم إرسال الطلب. سيصلك التقرير التفصيلي في تيليجرام.',perFarm:'نفس الكميات ستُطبق على كل مزرعة محددة.'},
    fr:{eyebrow:'COMMANDE DES CHÂTEAUX',title:'Commande Doomsday',subtitle:'Gérez tous vos châteaux depuis un seul écran.',search:'Rechercher par surnom ou ID',copy:'Copier les réglages',cancel:'Annuler',apply:'Appliquer',chooseSource:'Choisissez le château source.',chooseTargets:'Sélectionnez les châteaux cibles.',copied:'Réglages copiés.',noFarms:'Aucun château lié.',on:'ACTIF',off:'ARRÊTÉ',save:'Enregistrer tous les réglages',saving:'Enregistrement…',saved:'Réglages envoyés au bot.',back:'Retour',identity:'Identité du château',nickname:'Surnom du château',email:'E-mail IGG',password:'Nouveau mot de passe',passwordHint:'Laisser vide pour conserver le mot de passe',functions:'Fonctions automatiques',gather:'Collecte de ressources',food:'Nourriture',wood:'Bois',steel:'Acier',oil:'Pétrole',total:'Total des légions',maxFive:'Maximum 5 légions.',zombie:'Rebelles / zombies',maxLevel:'Niveau maximal',minLevel:'Niveau minimal',multiplier:'Multiplicateur',auto:'Auto : ×10, ×5, ×2, puis normal',normal:'Normal',shops:'Boutiques',arenaStore:'Boutique de l’arène',vipStore:'Boutique VIP — ressources uniquement',shopSafety:'Uniquement les objets sélectionnés disponibles. Gemmes et tentatives payantes bloquées.',points:'points',qty:'Qté',language:'Langue',selectTarget:'Sélectionnez des châteaux cibles.'},
    de:{eyebrow:'BURGEN-KOMMANDO',title:'Doomsday Kommando',subtitle:'Alle Burgen in einer Zentrale verwalten.',search:'Nach Name oder Burg-ID suchen',copy:'Einstellungen kopieren',cancel:'Abbrechen',apply:'Anwenden',chooseSource:'Quellburg wählen.',chooseTargets:'Zielburgen auswählen.',copied:'Einstellungen kopiert.',noFarms:'Keine Burgen verknüpft.',on:'AKTIV',off:'AUS',save:'Alle Einstellungen speichern',saving:'Speichern…',saved:'Einstellungen an den Bot gesendet.',back:'Zurück',identity:'Burgdaten',nickname:'Burgname',email:'IGG-E-Mail',password:'Neues Passwort',passwordHint:'Leer lassen, um das gespeicherte Passwort zu behalten',functions:'Automatisierungen',gather:'Ressourcen sammeln',food:'Nahrung',wood:'Holz',steel:'Stahl',oil:'Öl',total:'Legionen gesamt',maxFive:'Höchstens 5 Legionen.',zombie:'Rebellen / Zombies',maxLevel:'Maximale Stufe',minLevel:'Minimale Stufe',multiplier:'Multiplikator',auto:'Auto: ×10, ×5, ×2, dann normal',normal:'Normal',shops:'Läden',arenaStore:'Arena-Laden',vipStore:'VIP-Laden — nur Ressourcen',shopSafety:'Nur ausgewählte verfügbare Artikel. Edelsteine und bezahlte Versuche sind gesperrt.',points:'Punkte',qty:'Menge',language:'Sprache',selectTarget:'Zielburgen auswählen.'},
    it:{eyebrow:'COMANDO CASTELLI',title:'Comando Doomsday',subtitle:'Gestisci tutti i castelli da un solo pannello.',search:'Cerca per nome o ID',copy:'Copia impostazioni',cancel:'Annulla',apply:'Applica',chooseSource:'Scegli il castello sorgente.',chooseTargets:'Seleziona i castelli di destinazione.',copied:'Impostazioni copiate.',noFarms:'Nessun castello collegato.',on:'ATTIVO',off:'FERMO',save:'Salva tutte le impostazioni',saving:'Salvataggio…',saved:'Impostazioni inviate al bot.',back:'Indietro',identity:'Identità del castello',nickname:'Nome del castello',email:'E-mail IGG',password:'Nuova password',passwordHint:'Lascia vuoto per mantenere la password salvata',functions:'Funzioni automatiche',gather:'Raccolta risorse',food:'Cibo',wood:'Legno',steel:'Acciaio',oil:'Petrolio',total:'Legioni totali',maxFive:'Massimo 5 legioni.',zombie:'Ribelli / zombie',maxLevel:'Livello massimo',minLevel:'Livello minimo',multiplier:'Moltiplicatore',auto:'Auto: ×10, ×5, ×2, poi normale',normal:'Normale',shops:'Negozi',arenaStore:'Negozio Arena',vipStore:'Negozio VIP — solo risorse',shopSafety:'Solo oggetti selezionati e disponibili. Gemme e tentativi a pagamento sono bloccati.',points:'punti',qty:'Qtà',language:'Lingua',selectTarget:'Seleziona i castelli di destinazione.'},
    es:{eyebrow:'MANDO DE CASTILLOS',title:'Mando Doomsday',subtitle:'Gestiona todos tus castillos desde un panel.',search:'Buscar por nombre o ID',copy:'Copiar ajustes',cancel:'Cancelar',apply:'Aplicar',chooseSource:'Elige el castillo de origen.',chooseTargets:'Selecciona los castillos de destino.',copied:'Ajustes copiados.',noFarms:'No hay castillos vinculados.',on:'ACTIVO',off:'DETENIDO',save:'Guardar todos los ajustes',saving:'Guardando…',saved:'Ajustes enviados al bot.',back:'Volver',identity:'Identidad del castillo',nickname:'Nombre del castillo',email:'Correo IGG',password:'Nueva contraseña',passwordHint:'Déjalo vacío para conservar la guardada',functions:'Funciones automáticas',gather:'Recolección de recursos',food:'Comida',wood:'Madera',steel:'Acero',oil:'Petróleo',total:'Legiones totales',maxFive:'Máximo 5 legiones.',zombie:'Rebeldes / zombis',maxLevel:'Nivel máximo',minLevel:'Nivel mínimo',multiplier:'Multiplicador',auto:'Auto: ×10, ×5, ×2 y normal',normal:'Normal',shops:'Tiendas',arenaStore:'Tienda de Arena',vipStore:'Tienda VIP — solo recursos',shopSafety:'Solo artículos seleccionados y disponibles. Gemas e intentos de pago bloqueados.',points:'puntos',qty:'Cant.',language:'Idioma',selectTarget:'Selecciona castillos de destino.'},
    pt:{eyebrow:'COMANDO DOS CASTELOS',title:'Comando Doomsday',subtitle:'Gerencie todos os castelos em um painel.',search:'Buscar por nome ou ID',copy:'Copiar definições',cancel:'Cancelar',apply:'Aplicar',chooseSource:'Escolha o castelo de origem.',chooseTargets:'Selecione os castelos de destino.',copied:'Definições copiadas.',noFarms:'Nenhum castelo vinculado.',on:'ATIVO',off:'PARADO',save:'Salvar todas as definições',saving:'Salvando…',saved:'Definições enviadas ao bot.',back:'Voltar',identity:'Identidade do castelo',nickname:'Nome do castelo',email:'E-mail IGG',password:'Nova senha',passwordHint:'Deixe vazio para manter a senha salva',functions:'Funções automáticas',gather:'Coleta de recursos',food:'Comida',wood:'Madeira',steel:'Aço',oil:'Petróleo',total:'Total de legiões',maxFive:'Máximo de 5 legiões.',zombie:'Rebeldes / zumbis',maxLevel:'Nível máximo',minLevel:'Nível mínimo',multiplier:'Multiplicador',auto:'Auto: ×10, ×5, ×2 e normal',normal:'Normal',shops:'Lojas',arenaStore:'Loja da Arena',vipStore:'Loja VIP — apenas recursos',shopSafety:'Apenas itens selecionados e disponíveis. Gemas e tentativas pagos bloqueados.',points:'pontos',qty:'Qtd.',language:'Idioma',selectTarget:'Selecione castelos de destino.'},
    ru:{eyebrow:'УПРАВЛЕНИЕ ЗАМКАМИ',title:'Doomsday Командование',subtitle:'Все замки в одной панели.',search:'Поиск по имени или ID',copy:'Копировать настройки',cancel:'Отмена',apply:'Применить',chooseSource:'Выберите исходный замок.',chooseTargets:'Выберите целевые замки.',copied:'Настройки скопированы.',noFarms:'Нет привязанных замков.',on:'ВКЛ',off:'ВЫКЛ',save:'Сохранить все настройки',saving:'Сохранение…',saved:'Настройки отправлены боту.',back:'Назад',identity:'Данные замка',nickname:'Имя замка',email:'Почта IGG',password:'Новый пароль',passwordHint:'Оставьте пустым, чтобы сохранить пароль',functions:'Автоматические функции',gather:'Сбор ресурсов',food:'Еда',wood:'Дерево',steel:'Сталь',oil:'Нефть',total:'Всего легионов',maxFive:'Не более 5 легионов.',zombie:'Повстанцы / зомби',maxLevel:'Макс. уровень',minLevel:'Мин. уровень',multiplier:'Множитель',auto:'Авто: ×10, ×5, ×2, затем обычно',normal:'Обычно',shops:'Магазины',arenaStore:'Магазин арены',vipStore:'VIP-магазин — только ресурсы',shopSafety:'Только выбранные доступные товары. Самоцветы и платные попытки заблокированы.',points:'очки',qty:'Кол.',language:'Язык',selectTarget:'Выберите целевые замки.'}
  };
  var TRANSFER_OV = {
    fr:{transfer:'Transférer des ressources',transferTarget:'ID du château destinataire',transferHint:'Sélectionnez les fermes ci-dessous, puis la quantité envoyée par chaque ferme.',selectedFarms:'Fermes sélectionnées',enterAmounts:'Quantité par ferme',sendTransfer:'Envoyer',confirmTransfer:'Confirmer le transfert',close:'Fermer',transferInvalid:'Saisissez un ID valide, choisissez au moins une ferme et une quantité.',transferSent:'Demande envoyée. Le rapport détaillé arrivera dans Telegram.',perFarm:'Les mêmes quantités s’appliquent à chaque ferme sélectionnée.'},
    de:{transfer:'Ressourcen übertragen',transferTarget:'ID der empfangenden Burg',transferHint:'Farmen unten auswählen und die Menge je Farm eingeben.',selectedFarms:'Ausgewählte Farmen',enterAmounts:'Menge je Farm',sendTransfer:'Ressourcen senden',confirmTransfer:'Transfer bestätigen',close:'Schließen',transferInvalid:'Gültige Ziel-ID, mindestens eine Farm und eine Ressourcenmenge eingeben.',transferSent:'Transferanfrage gesendet. Der Detailbericht folgt in Telegram.',perFarm:'Dieselben Mengen gelten für jede ausgewählte Farm.'},
    it:{transfer:'Trasferisci risorse',transferTarget:'ID castello destinatario',transferHint:'Seleziona le fattorie e indica la quantità inviata da ciascuna.',selectedFarms:'Fattorie selezionate',enterAmounts:'Quantità per fattoria',sendTransfer:'Invia risorse',confirmTransfer:'Conferma trasferimento',close:'Chiudi',transferInvalid:'Inserisci un ID valido, scegli almeno una fattoria e una quantità.',transferSent:'Richiesta inviata. Il rapporto dettagliato arriverà su Telegram.',perFarm:'Le stesse quantità valgono per ogni fattoria selezionata.'},
    es:{transfer:'Transferir recursos',transferTarget:'ID del castillo receptor',transferHint:'Selecciona las granjas e indica la cantidad que enviará cada una.',selectedFarms:'Granjas seleccionadas',enterAmounts:'Cantidad por granja',sendTransfer:'Enviar recursos',confirmTransfer:'Confirmar transferencia',close:'Cerrar',transferInvalid:'Escribe un ID válido, elige al menos una granja y una cantidad.',transferSent:'Solicitud enviada. El informe detallado llegará por Telegram.',perFarm:'Las mismas cantidades se aplican a cada granja seleccionada.'},
    pt:{transfer:'Transferir recursos',transferTarget:'ID do castelo de destino',transferHint:'Selecione as fazendas e informe a quantidade enviada por cada uma.',selectedFarms:'Fazendas selecionadas',enterAmounts:'Quantidade por fazenda',sendTransfer:'Enviar recursos',confirmTransfer:'Confirmar transferência',close:'Fechar',transferInvalid:'Informe um ID válido, selecione ao menos uma fazenda e uma quantidade.',transferSent:'Solicitação enviada. O relatório detalhado chegará no Telegram.',perFarm:'As mesmas quantidades valem para cada fazenda selecionada.'},
    ru:{transfer:'Передать ресурсы',transferTarget:'ID замка-получателя',transferHint:'Выберите фермы ниже и укажите объём с каждой фермы.',selectedFarms:'Выбранные фермы',enterAmounts:'Количество с каждой фермы',sendTransfer:'Отправить ресурсы',confirmTransfer:'Подтвердить передачу',close:'Закрыть',transferInvalid:'Укажите верный ID, выберите ферму и объём ресурсов.',transferSent:'Запрос отправлен. Подробный отчёт придёт в Telegram.',perFarm:'Одинаковые объёмы применяются ко всем выбранным фермам.'}
  };

  EN.transferHint='Choose several farms and fill one shared resource target.';
  EN.enterAmounts='Aggregate resource target';
  EN.aggregateHint='The selected farms send in order until the shared target is complete. Later farms stop automatically.';
  EN.aggregateAmounts='Enter the total required from all selected farms together, not an amount per farm.';
  EN.selectAll='Select all'; EN.clearAll='Clear';
  Object.assign(OV.ar,{transferHint:'اختر عدة مزارع وحدد إجمالي الموارد المطلوب منها كلها.',enterAmounts:'إجمالي الموارد المطلوب',aggregateHint:'المزارع المحددة ترسل بالترتيب حتى يكتمل الإجمالي المطلوب، ثم تتوقف باقي المزارع تلقائيًا.',aggregateAmounts:'اكتب إجمالي المطلوب من كل المزارع المحددة معًا، وليس كمية من كل مزرعة.',selectAll:'تحديد الكل',clearAll:'إلغاء التحديد',castlesTab:'القلاع',castleSettings:'إعدادات القلعة',protectedSection:'قسم محمي',notAuthorized:'غير مصرح لك باستخدام هذه الخاصية.'});
  var TRANSFER_PAGE_OV = {
    fr:{transferHint:'Choisissez plusieurs fermes et un objectif total partagé.',enterAmounts:'Objectif total de ressources',aggregateHint:'Les fermes envoient dans l’ordre jusqu’à atteindre l’objectif total, puis les suivantes s’arrêtent.',aggregateAmounts:'Saisissez le total demandé à toutes les fermes réunies, pas une quantité par ferme.',selectAll:'Tout sélectionner',clearAll:'Effacer'},
    de:{transferHint:'Mehrere Farmen wählen und ein gemeinsames Gesamtziel festlegen.',enterAmounts:'Gesamtes Ressourcenziel',aggregateHint:'Die Farmen senden der Reihe nach bis zum Gesamtziel; spätere Farmen stoppen automatisch.',aggregateAmounts:'Gesamtmenge für alle ausgewählten Farmen zusammen eingeben, nicht je Farm.',selectAll:'Alle auswählen',clearAll:'Leeren'},
    it:{transferHint:'Scegli più fattorie e un unico obiettivo totale.',enterAmounts:'Obiettivo totale risorse',aggregateHint:'Le fattorie inviano in ordine fino al totale richiesto; le successive si fermano automaticamente.',aggregateAmounts:'Inserisci il totale richiesto da tutte le fattorie insieme, non per singola fattoria.',selectAll:'Seleziona tutto',clearAll:'Cancella'},
    es:{transferHint:'Elige varias granjas y un objetivo total compartido.',enterAmounts:'Objetivo total de recursos',aggregateHint:'Las granjas envían en orden hasta completar el total; las demás se detienen automáticamente.',aggregateAmounts:'Escribe el total requerido entre todas las granjas, no una cantidad por granja.',selectAll:'Seleccionar todo',clearAll:'Limpiar'},
    pt:{transferHint:'Escolha várias fazendas e uma meta total compartilhada.',enterAmounts:'Meta total de recursos',aggregateHint:'As fazendas enviam em ordem até atingir a meta; as demais param automaticamente.',aggregateAmounts:'Informe o total desejado de todas as fazendas juntas, não por fazenda.',selectAll:'Selecionar tudo',clearAll:'Limpar'},
    ru:{transferHint:'Выберите несколько ферм и общую цель ресурсов.',enterAmounts:'Общая цель ресурсов',aggregateHint:'Фермы отправляют по очереди до достижения общей цели; остальные остановятся автоматически.',aggregateAmounts:'Укажите общий объём со всех выбранных ферм, а не объём с каждой.',selectAll:'Выбрать все',clearAll:'Очистить'}
  };
  Object.keys(TRANSFER_PAGE_OV).forEach(function(lang){Object.assign(TRANSFER_OV[lang],TRANSFER_PAGE_OV[lang]);});
  Object.assign(OV,{
    'zh-cn':{eyebrow:'城堡指挥中心',title:'Doomsday 指挥中心',subtitle:'在一个面板中管理所有城堡。',telegram:'Telegram ID',search:'按名称或城堡 ID 搜索',copy:'复制设置',cancel:'取消',apply:'应用设置',chooseSource:'选择来源城堡。',chooseTargets:'选择一个或多个目标城堡。',copied:'设置已复制到所选城堡。',noFarms:'此 Telegram 账号没有关联城堡。',on:'运行中',off:'已停止',save:'保存全部设置',saving:'正在保存…',saved:'设置已发送给机器人。',openTelegram:'请从 Telegram 机器人打开此页面。',invalid:'城堡数据无效，请从机器人重新打开。',back:'返回',identity:'城堡信息',nickname:'城堡名称',email:'IGG 邮箱',password:'新密码',passwordHint:'留空以保留已保存的密码',functions:'自动化功能',gather:'资源采集',food:'食物',wood:'木材',steel:'钢材',oil:'石油',total:'军团总数',maxFive:'最多 5 个军团。',zombie:'叛军 / 丧尸设置',maxLevel:'最高等级',minLevel:'最低等级',multiplier:'倍率',auto:'自动：×10、×5、×2，然后普通',normal:'普通',shops:'商店',arenaStore:'竞技场商店',vipStore:'VIP 商店 — 仅资源商品',shopSafety:'只购买当前可用的已选商品。永久禁止钻石和付费次数。',points:'积分',vip:'VIP',qty:'数量',language:'语言',source:'来源',targets:'目标',selectTarget:'请先选择目标城堡。',transfer:'发送资源',transferTarget:'接收城堡 ID',transferHint:'选择多个农场并填写一个共同的资源总目标。',selectedFarms:'已选农场',enterAmounts:'资源总目标',sendTransfer:'发送资源',confirmTransfer:'确认发送',transferInvalid:'请输入有效目标 ID，至少选择一个农场并填写资源数量。',transferSent:'请求已发送，详细报告将通过 Telegram 发送。',aggregateHint:'所选农场按顺序发送，达到总目标后其余农场自动停止。',aggregateAmounts:'填写所有所选农场合计需要的数量，而不是每个农场的数量。',selectAll:'全选',clearAll:'清除'},
    'zh-tw':{eyebrow:'城堡指揮中心',title:'Doomsday 指揮中心',subtitle:'在一個面板中管理所有城堡。',telegram:'Telegram ID',search:'依名稱或城堡 ID 搜尋',copy:'複製設定',cancel:'取消',apply:'套用設定',chooseSource:'選擇來源城堡。',chooseTargets:'選擇一個或多個目標城堡。',copied:'設定已複製到所選城堡。',noFarms:'此 Telegram 帳號沒有連結城堡。',on:'運行中',off:'已停止',save:'儲存全部設定',saving:'正在儲存…',saved:'設定已傳送給機器人。',openTelegram:'請從 Telegram 機器人開啟此頁面。',invalid:'城堡資料無效，請從機器人重新開啟。',back:'返回',identity:'城堡資訊',nickname:'城堡名稱',email:'IGG 信箱',password:'新密碼',passwordHint:'留空以保留已儲存的密碼',functions:'自動化功能',gather:'資源採集',food:'食物',wood:'木材',steel:'鋼材',oil:'石油',total:'軍團總數',maxFive:'最多 5 個軍團。',zombie:'叛軍 / 喪屍設定',maxLevel:'最高等級',minLevel:'最低等級',multiplier:'倍率',auto:'自動：×10、×5、×2，然後普通',normal:'普通',shops:'商店',arenaStore:'競技場商店',vipStore:'VIP 商店 — 僅資源商品',shopSafety:'只購買目前可用的已選商品。永久禁止鑽石和付費次數。',points:'積分',vip:'VIP',qty:'數量',language:'語言',source:'來源',targets:'目標',selectTarget:'請先選擇目標城堡。',transfer:'傳送資源',transferTarget:'接收城堡 ID',transferHint:'選擇多個農場並填寫一個共同的資源總目標。',selectedFarms:'已選農場',enterAmounts:'資源總目標',sendTransfer:'傳送資源',confirmTransfer:'確認傳送',transferInvalid:'請輸入有效目標 ID，至少選擇一個農場並填寫資源數量。',transferSent:'請求已傳送，詳細報告將透過 Telegram 傳送。',aggregateHint:'所選農場依序傳送，達到總目標後其餘農場自動停止。',aggregateAmounts:'填寫所有所選農場合計需要的數量，而不是每個農場的數量。',selectAll:'全選',clearAll:'清除'},
    id:{eyebrow:'PUSAT KOMANDO KASTEL',title:'Komando Doomsday',subtitle:'Kelola semua kastel dari satu panel.',telegram:'ID Telegram',search:'Cari nama atau ID kastel',copy:'Salin pengaturan',cancel:'Batal',apply:'Terapkan pengaturan',chooseSource:'Pilih kastel sumber.',chooseTargets:'Pilih satu atau beberapa kastel tujuan.',copied:'Pengaturan disalin ke kastel terpilih.',noFarms:'Tidak ada kastel yang terhubung ke akun Telegram ini.',on:'AKTIF',off:'BERHENTI',save:'Simpan semua pengaturan',saving:'Menyimpan…',saved:'Pengaturan dikirim ke bot.',openTelegram:'Buka halaman ini dari bot Telegram.',invalid:'Data kastel tidak valid. Buka kembali dari bot.',back:'Kembali',identity:'Identitas kastel',nickname:'Nama kastel',email:'Email IGG',password:'Kata sandi baru',passwordHint:'Kosongkan untuk mempertahankan kata sandi tersimpan',functions:'Fungsi otomatis',gather:'Pengumpulan sumber daya',food:'Makanan',wood:'Kayu',steel:'Baja',oil:'Minyak',total:'Total legiun',maxFive:'Maksimal 5 legiun.',zombie:'Pengaturan pemberontak / zombie',maxLevel:'Level maksimum',minLevel:'Level minimum',multiplier:'Pengali',auto:'Otomatis: ×10, ×5, ×2, lalu normal',normal:'Normal',shops:'Toko',arenaStore:'Toko Arena',vipStore:'Toko VIP — hanya sumber daya',shopSafety:'Bot hanya membeli semua barang terpilih yang tersedia. Permata dan percobaan berbayar selalu diblokir.',points:'poin',vip:'VIP',qty:'Jml',language:'Bahasa',source:'Sumber',targets:'Tujuan',selectTarget:'Pilih kastel tujuan terlebih dahulu.',transfer:'Kirim sumber daya',transferTarget:'ID kastel penerima',transferHint:'Pilih beberapa farm dan isi satu target total bersama.',selectedFarms:'Farm terpilih',enterAmounts:'Target total sumber daya',sendTransfer:'Kirim sumber daya',confirmTransfer:'Konfirmasi pengiriman',transferInvalid:'Masukkan ID tujuan valid, pilih minimal satu farm, dan isi jumlah sumber daya.',transferSent:'Permintaan dikirim. Laporan rinci akan dikirim melalui Telegram.',aggregateHint:'Farm mengirim berurutan hingga target total tercapai; farm berikutnya berhenti otomatis.',aggregateAmounts:'Masukkan total dari semua farm terpilih, bukan jumlah per farm.',selectAll:'Pilih semua',clearAll:'Hapus'},
    th:{eyebrow:'ศูนย์บัญชาการปราสาท',title:'ศูนย์บัญชาการ Doomsday',subtitle:'จัดการทุกปราสาทจากแผงเดียว',telegram:'Telegram ID',search:'ค้นหาด้วยชื่อหรือ ID ปราสาท',copy:'คัดลอกการตั้งค่า',cancel:'ยกเลิก',apply:'ใช้การตั้งค่า',chooseSource:'เลือกปราสาทต้นทาง',chooseTargets:'เลือกปราสาทปลายทางหนึ่งแห่งขึ้นไป',copied:'คัดลอกการตั้งค่าไปยังปราสาทที่เลือกแล้ว',noFarms:'ไม่มีปราสาทที่เชื่อมกับบัญชี Telegram นี้',on:'เปิด',off:'หยุด',save:'บันทึกการตั้งค่าทั้งหมด',saving:'กำลังบันทึก…',saved:'ส่งการตั้งค่าไปยังบอตแล้ว',openTelegram:'เปิดหน้านี้จากบอต Telegram',invalid:'ข้อมูลปราสาทไม่ถูกต้อง โปรดเปิดใหม่จากบอต',back:'กลับ',identity:'ข้อมูลปราสาท',nickname:'ชื่อปราสาท',email:'อีเมล IGG',password:'รหัสผ่านใหม่',passwordHint:'เว้นว่างเพื่อใช้รหัสผ่านเดิม',functions:'ฟังก์ชันอัตโนมัติ',gather:'รวบรวมทรัพยากร',food:'อาหาร',wood:'ไม้',steel:'เหล็ก',oil:'น้ำมัน',total:'จำนวนกองทัพรวม',maxFive:'รวมได้ไม่เกิน 5 กองทัพ',zombie:'การตั้งค่ากบฏ / ซอมบี้',maxLevel:'ระดับสูงสุด',minLevel:'ระดับต่ำสุด',multiplier:'ตัวคูณ',auto:'อัตโนมัติ: ×10, ×5, ×2 แล้วปกติ',normal:'ปกติ',shops:'ร้านค้า',arenaStore:'ร้านค้าอารีนา',vipStore:'ร้าน VIP — ใช้ทรัพยากรเท่านั้น',shopSafety:'บอตซื้อสินค้าที่เลือกและมีอยู่ทั้งหมดเท่านั้น ปิดกั้นเพชรและจำนวนครั้งแบบเสียเงินถาวร',points:'แต้ม',vip:'VIP',qty:'จำนวน',language:'ภาษา',source:'ต้นทาง',targets:'ปลายทาง',selectTarget:'เลือกปราสาทปลายทางก่อน',transfer:'ส่งทรัพยากร',transferTarget:'ID ปราสาทผู้รับ',transferHint:'เลือกหลายฟาร์มและกำหนดเป้าหมายรวมหนึ่งชุด',selectedFarms:'ฟาร์มที่เลือก',enterAmounts:'เป้าหมายทรัพยากรรวม',sendTransfer:'ส่งทรัพยากร',confirmTransfer:'ยืนยันการส่ง',transferInvalid:'ใส่ ID เป้าหมายที่ถูกต้อง เลือกอย่างน้อยหนึ่งฟาร์ม และใส่จำนวนทรัพยากร',transferSent:'ส่งคำขอแล้ว รายงานละเอียดจะส่งทาง Telegram',aggregateHint:'ฟาร์มจะส่งตามลำดับจนถึงเป้าหมายรวม แล้วฟาร์มที่เหลือจะหยุดอัตโนมัติ',aggregateAmounts:'ใส่ยอดรวมที่ต้องการจากทุกฟาร์ม ไม่ใช่จำนวนต่อฟาร์ม',selectAll:'เลือกทั้งหมด',clearAll:'ล้าง'},
    tr:{eyebrow:'KALE KOMUTA MERKEZİ',title:'Doomsday Komuta',subtitle:'Tüm kaleleri tek panelden yönetin.',telegram:'Telegram ID',search:'Ad veya kale ID ile ara',copy:'Ayarları kopyala',cancel:'İptal',apply:'Ayarları uygula',chooseSource:'Kaynak kaleyi seçin.',chooseTargets:'Bir veya daha fazla hedef kale seçin.',copied:'Ayarlar seçili kalelere kopyalandı.',noFarms:'Bu Telegram hesabına bağlı kale yok.',on:'AÇIK',off:'DURDU',save:'Tüm ayarları kaydet',saving:'Kaydediliyor…',saved:'Ayarlar bota gönderildi.',openTelegram:'Bu sayfayı Telegram botundan açın.',invalid:'Kale verileri geçersiz. Sayfayı bottan yeniden açın.',back:'Geri',identity:'Kale bilgileri',nickname:'Kale adı',email:'IGG e-posta',password:'Yeni parola',passwordHint:'Kayıtlı parolayı korumak için boş bırakın',functions:'Otomasyon işlevleri',gather:'Kaynak toplama',food:'Yiyecek',wood:'Odun',steel:'Çelik',oil:'Petrol',total:'Toplam lejyon',maxFive:'Toplam en fazla 5 lejyon olabilir.',zombie:'Asi / zombi ayarları',maxLevel:'En yüksek seviye',minLevel:'En düşük seviye',multiplier:'Çarpan',auto:'Otomatik: ×10, ×5, ×2, sonra normal',normal:'Normal',shops:'Mağazalar',arenaStore:'Arena Mağazası',vipStore:'VIP Mağazası — yalnız kaynakla',shopSafety:'Bot yalnız seçili ve mevcut tüm ürünleri alır. Elmas ve ücretli denemeler kalıcı olarak engellidir.',points:'puan',vip:'VIP',qty:'Adet',language:'Dil',source:'Kaynak',targets:'Hedefler',selectTarget:'Önce hedef kaleleri seçin.',transfer:'Kaynak gönder',transferTarget:'Alıcı kale ID',transferHint:'Birden fazla çiftlik seçin ve tek bir ortak toplam hedef girin.',selectedFarms:'Seçili çiftlikler',enterAmounts:'Toplam kaynak hedefi',sendTransfer:'Kaynak gönder',confirmTransfer:'Gönderimi onayla',transferInvalid:'Geçerli hedef ID, en az bir çiftlik ve kaynak miktarı girin.',transferSent:'İstek gönderildi. Ayrıntılı rapor Telegram üzerinden gelecek.',aggregateHint:'Çiftlikler toplam hedef tamamlanana kadar sırayla gönderir; sonrakiler otomatik durur.',aggregateAmounts:'Çiftlik başına değil, tüm seçili çiftliklerin toplamını girin.',selectAll:'Tümünü seç',clearAll:'Temizle'},
    ko:{eyebrow:'성 지휘 센터',title:'Doomsday 지휘',subtitle:'모든 성을 하나의 패널에서 관리하세요.',telegram:'Telegram ID',search:'이름 또는 성 ID로 검색',copy:'설정 복사',cancel:'취소',apply:'설정 적용',chooseSource:'원본 성을 선택하세요.',chooseTargets:'하나 이상의 대상 성을 선택하세요.',copied:'선택한 성으로 설정을 복사했습니다.',noFarms:'이 Telegram 계정에 연결된 성이 없습니다.',on:'실행 중',off:'중지됨',save:'모든 설정 저장',saving:'저장 중…',saved:'설정을 봇으로 전송했습니다.',openTelegram:'Telegram 봇에서 이 페이지를 여세요.',invalid:'성 데이터가 잘못되었습니다. 봇에서 다시 여세요.',back:'뒤로',identity:'성 정보',nickname:'성 이름',email:'IGG 이메일',password:'새 비밀번호',passwordHint:'저장된 비밀번호를 유지하려면 비워 두세요',functions:'자동화 기능',gather:'자원 채집',food:'식량',wood:'목재',steel:'강철',oil:'석유',total:'총 군단 수',maxFive:'최대 5개 군단입니다.',zombie:'반란군 / 좀비 설정',maxLevel:'최고 레벨',minLevel:'최저 레벨',multiplier:'배수',auto:'자동: ×10, ×5, ×2 후 일반',normal:'일반',shops:'상점',arenaStore:'아레나 상점',vipStore:'VIP 상점 — 자원 상품만',shopSafety:'선택했고 현재 구매 가능한 모든 상품만 삽니다. 다이아와 유료 횟수는 항상 차단됩니다.',points:'포인트',vip:'VIP',qty:'수량',language:'언어',source:'원본',targets:'대상',selectTarget:'먼저 대상 성을 선택하세요.',transfer:'자원 보내기',transferTarget:'받는 성 ID',transferHint:'여러 농장을 선택하고 하나의 공동 총목표를 입력하세요.',selectedFarms:'선택한 농장',enterAmounts:'총 자원 목표',sendTransfer:'자원 보내기',confirmTransfer:'전송 확인',transferInvalid:'올바른 대상 ID, 하나 이상의 농장, 자원 수량을 입력하세요.',transferSent:'요청을 전송했습니다. 상세 보고서는 Telegram으로 전송됩니다.',aggregateHint:'선택한 농장이 순서대로 보내며 총목표에 도달하면 나머지는 자동 중지됩니다.',aggregateAmounts:'농장별 수량이 아니라 선택한 모든 농장의 합계를 입력하세요.',selectAll:'전체 선택',clearAll:'지우기'},
    ja:{eyebrow:'城指令センター',title:'Doomsday コマンド',subtitle:'すべての城を一つのパネルで管理します。',telegram:'Telegram ID',search:'名前または城 ID で検索',copy:'設定をコピー',cancel:'キャンセル',apply:'設定を適用',chooseSource:'コピー元の城を選択してください。',chooseTargets:'対象の城を一つ以上選択してください。',copied:'選択した城に設定をコピーしました。',noFarms:'この Telegram アカウントに城が登録されていません。',on:'稼働中',off:'停止中',save:'すべての設定を保存',saving:'保存中…',saved:'設定をボットに送信しました。',openTelegram:'Telegram ボットからこのページを開いてください。',invalid:'城のデータが無効です。ボットから開き直してください。',back:'戻る',identity:'城の情報',nickname:'城の名前',email:'IGG メール',password:'新しいパスワード',passwordHint:'保存済みパスワードを維持する場合は空欄',functions:'自動化機能',gather:'資源採集',food:'食料',wood:'木材',steel:'鋼鉄',oil:'石油',total:'軍団の合計',maxFive:'最大 5 軍団です。',zombie:'反乱軍 / ゾンビ設定',maxLevel:'最高レベル',minLevel:'最低レベル',multiplier:'倍率',auto:'自動：×10、×5、×2、その後通常',normal:'通常',shops:'ショップ',arenaStore:'アリーナショップ',vipStore:'VIP ショップ — 資源商品のみ',shopSafety:'選択済みで現在購入可能な商品をすべて購入します。ダイヤと有料回数は常に禁止です。',points:'ポイント',vip:'VIP',qty:'数量',language:'言語',source:'コピー元',targets:'対象',selectTarget:'先に対象の城を選択してください。',transfer:'資源を送る',transferTarget:'受取先の城 ID',transferHint:'複数の農場を選び、共通の合計目標を一つ入力します。',selectedFarms:'選択した農場',enterAmounts:'資源の合計目標',sendTransfer:'資源を送る',confirmTransfer:'送信を確認',transferInvalid:'有効な対象 ID、1 つ以上の農場、資源量を入力してください。',transferSent:'リクエストを送信しました。詳細レポートは Telegram に届きます。',aggregateHint:'選択した農場が順番に送り、合計目標に達すると残りは自動停止します。',aggregateAmounts:'農場ごとの量ではなく、選択した全農場の合計を入力してください。',selectAll:'すべて選択',clearAll:'クリア'},
    vi:{eyebrow:'TRUNG TÂM CHỈ HUY LÂU ĐÀI',title:'Chỉ huy Doomsday',subtitle:'Quản lý mọi lâu đài từ một bảng điều khiển.',telegram:'ID Telegram',search:'Tìm theo tên hoặc ID lâu đài',copy:'Sao chép cài đặt',cancel:'Hủy',apply:'Áp dụng cài đặt',chooseSource:'Chọn lâu đài nguồn.',chooseTargets:'Chọn một hoặc nhiều lâu đài đích.',copied:'Đã sao chép cài đặt sang các lâu đài đã chọn.',noFarms:'Không có lâu đài liên kết với tài khoản Telegram này.',on:'ĐANG CHẠY',off:'ĐÃ DỪNG',save:'Lưu mọi cài đặt',saving:'Đang lưu…',saved:'Đã gửi cài đặt tới bot.',openTelegram:'Mở trang này từ bot Telegram.',invalid:'Dữ liệu lâu đài không hợp lệ. Hãy mở lại từ bot.',back:'Quay lại',identity:'Thông tin lâu đài',nickname:'Tên lâu đài',email:'Email IGG',password:'Mật khẩu mới',passwordHint:'Để trống để giữ mật khẩu đã lưu',functions:'Chức năng tự động',gather:'Thu thập tài nguyên',food:'Lương thực',wood:'Gỗ',steel:'Thép',oil:'Dầu',total:'Tổng số quân đoàn',maxFive:'Tối đa 5 quân đoàn.',zombie:'Cài đặt phiến quân / zombie',maxLevel:'Cấp cao nhất',minLevel:'Cấp thấp nhất',multiplier:'Hệ số',auto:'Tự động: ×10, ×5, ×2 rồi thường',normal:'Thường',shops:'Cửa hàng',arenaStore:'Cửa hàng Đấu trường',vipStore:'Cửa hàng VIP — chỉ dùng tài nguyên',shopSafety:'Bot chỉ mua toàn bộ vật phẩm đã chọn và đang có. Kim cương và lượt trả phí luôn bị chặn.',points:'điểm',vip:'VIP',qty:'SL',language:'Ngôn ngữ',source:'Nguồn',targets:'Đích',selectTarget:'Hãy chọn lâu đài đích trước.',transfer:'Gửi tài nguyên',transferTarget:'ID lâu đài nhận',transferHint:'Chọn nhiều nông trại và nhập một mục tiêu tổng chung.',selectedFarms:'Nông trại đã chọn',enterAmounts:'Mục tiêu tổng tài nguyên',sendTransfer:'Gửi tài nguyên',confirmTransfer:'Xác nhận gửi',transferInvalid:'Nhập ID đích hợp lệ, chọn ít nhất một nông trại và nhập lượng tài nguyên.',transferSent:'Đã gửi yêu cầu. Báo cáo chi tiết sẽ được gửi qua Telegram.',aggregateHint:'Các nông trại gửi lần lượt đến khi đủ mục tiêu tổng; nông trại sau sẽ tự dừng.',aggregateAmounts:'Nhập tổng cần từ tất cả nông trại đã chọn, không phải số lượng mỗi nông trại.',selectAll:'Chọn tất cả',clearAll:'Xóa'}
  });
  Object.assign(EN,{pendingConfirmation:'Request sent. Wait for confirmation from the bot.'});
  Object.assign(OV.ar,{pendingConfirmation:'تم إرسال الطلب، انتظر تأكيد البوت.'});

  var REGION_OV = {
    ar:{region:'المنطقة',ordinaryResources:'الموارد العادية المفتوحة',stockUpdated:'آخر تأكيد',stockUnavailable:'في انتظار اتصال البوت التالي',stockLimitNote:'قد تكون الكمية المرسلة أقل بسبب حدود مركز التجارة والضريبة وحد استقبال القلعة.'},
    fr:{region:'Région',ordinaryResources:'Ressources ordinaires ouvertes',stockUpdated:'Dernière confirmation',stockUnavailable:'En attente de la prochaine connexion du bot',stockLimitNote:'L’envoi réel peut être inférieur selon les limites, la taxe et le destinataire.'},
    de:{region:'Region',ordinaryResources:'Offene normale Ressourcen',stockUpdated:'Zuletzt bestätigt',stockUnavailable:'Warten auf die nächste Bot-Verbindung',stockLimitNote:'Die tatsächliche Sendung kann durch Limits, Steuer und Empfänger geringer sein.'},
    it:{region:'Regione',ordinaryResources:'Risorse ordinarie aperte',stockUpdated:'Ultima conferma',stockUnavailable:'In attesa della prossima connessione del bot',stockLimitNote:'L’invio effettivo può essere inferiore per limiti, tasse e destinatario.'},
    es:{region:'Región',ordinaryResources:'Recursos ordinarios abiertos',stockUpdated:'Última confirmación',stockUnavailable:'Esperando la próxima conexión del bot',stockLimitNote:'El envío real puede ser menor por límites, impuestos y receptor.'},
    pt:{region:'Região',ordinaryResources:'Recursos comuns abertos',stockUpdated:'Última confirmação',stockUnavailable:'Aguardando a próxima conexão do bot',stockLimitNote:'O envio real pode ser menor por limites, imposto e recebedor.'},
    ru:{region:'Регион',ordinaryResources:'Открытые обычные ресурсы',stockUpdated:'Последнее подтверждение',stockUnavailable:'Ожидание следующего подключения бота',stockLimitNote:'Фактическая отправка может быть меньше из-за лимитов, налога и получателя.'},
    'zh-cn':{region:'区域',ordinaryResources:'可用普通资源',stockUpdated:'最后确认',stockUnavailable:'等待机器人下次连接',stockLimitNote:'实际发送量可能受交易站、税费和接收上限影响。'},
    'zh-tw':{region:'區域',ordinaryResources:'可用一般資源',stockUpdated:'最後確認',stockUnavailable:'等待機器人下次連線',stockLimitNote:'實際傳送量可能受交易站、稅費和接收上限影響。'},
    id:{region:'Wilayah',ordinaryResources:'Sumber daya biasa terbuka',stockUpdated:'Konfirmasi terakhir',stockUnavailable:'Menunggu koneksi bot berikutnya',stockLimitNote:'Jumlah terkirim dapat lebih kecil karena batas, pajak, dan penerima.'},
    th:{region:'ภูมิภาค',ordinaryResources:'ทรัพยากรปกติที่เปิดใช้',stockUpdated:'ยืนยันล่าสุด',stockUnavailable:'รอการเชื่อมต่อบอตครั้งถัดไป',stockLimitNote:'จำนวนที่ส่งจริงอาจน้อยลงจากข้อจำกัด ภาษี และผู้รับ'},
    tr:{region:'Bölge',ordinaryResources:'Açık normal kaynaklar',stockUpdated:'Son doğrulama',stockUnavailable:'Sonraki bot bağlantısı bekleniyor',stockLimitNote:'Gerçek gönderim limit, vergi ve alıcı nedeniyle daha düşük olabilir.'},
    ko:{region:'지역',ordinaryResources:'가방 밖 일반 자원',stockUpdated:'마지막 확인',stockUnavailable:'다음 봇 연결 대기 중',stockLimitNote:'교역소 한도, 세금, 수신 한도로 실제 전송량은 더 적을 수 있습니다.'},
    ja:{region:'地域',ordinaryResources:'バッグ外の通常資源',stockUpdated:'最終確認',stockUnavailable:'次のボット接続を待機中',stockLimitNote:'交易所上限、税、受取上限により実際の送信量は少なくなる場合があります。'},
    vi:{region:'Khu vực',ordinaryResources:'Tài nguyên thường đang mở',stockUpdated:'Xác nhận gần nhất',stockUnavailable:'Đang chờ lần kết nối bot tiếp theo',stockLimitNote:'Lượng gửi thực tế có thể thấp hơn do giới hạn, thuế và bên nhận.'}
  };

  var FEATURE_EN = {
    resource_challenge:'Select resource challenge',radar:'Radar Station',zombie:'Attack rebels / zombies',gathering:'Gather resources',daily_missions:'Daily Missions',training:'Train troops and speedup task',refinery:'Refine Common Ore',alliance_gifts:'Alliance gifts',mail_rewards:'Mail rewards',vip_daily_gift:'Daily VIP chest',alliance_technology:'Marked alliance technology',territory_rewards:'Territory rewards',event_rewards:'Free and event rewards',police_normal:'Police normal free search',police_advanced:'Police advanced free search',arena_of_doom:'Arena of Doom — free attempts',arena_store:'Buy every selected item currently available from Arena Store',vip_store:'Buy every selected item currently available from VIP Store'
  };
  var FEATURE_AR = {
    resource_challenge:'اختيار تحدي جمع الموارد',radar:'محطة الرادار',zombie:'مهاجمة المتمردين / الزومبي',gathering:'جمع الموارد',daily_missions:'المهام اليومية',training:'تجنيد الجنود ومهمة التسريع',refinery:'صقل الخام العادي',alliance_gifts:'هدايا التحالف',mail_rewards:'جوائز البريد',vip_daily_gift:'صندوق VIP اليومي',alliance_technology:'تقنية التحالف المحددة',territory_rewards:'جوائز الإقليم',event_rewards:'الجوائز المجانية والأحداث',police_normal:'بحث مركز الشرطة العادي المجاني',police_advanced:'بحث مركز الشرطة المتقدم المجاني',arena_of_doom:'حلبة الهلاك — المحاولات المجانية',arena_store:'شراء كل المتاح من العناصر المختارة في متجر الحلبة',vip_store:'شراء كل المتاح من العناصر المختارة في متجر VIP'
  };
  FEATURE_EN.mysterious_merchant = 'Mysterious Merchant — buy everything available with resources and use every free refresh';
  FEATURE_AR.mysterious_merchant = 'التاجر الغامض — شراء كل المتاح بالموارد واستخدام كل التحديثات المجانية';
  var FEATURE_OTHER = {
    fr:{alliance_help:'Aider les membres de l’alliance',resource_challenge:'Choisir le défi de collecte',radar:'Station radar',zombie:'Attaquer les rebelles / zombies',gathering:'Collecter des ressources',daily_missions:'Missions quotidiennes',training:'Entraînement et accélération',refinery:'Raffiner le minerai commun',alliance_gifts:'Cadeaux d’alliance',mail_rewards:'Récompenses du courrier',vip_daily_gift:'Coffre VIP quotidien',alliance_technology:'Technologie d’alliance marquée',territory_rewards:'Récompenses de territoire',event_rewards:'Récompenses gratuites et événements',police_normal:'Recherche normale gratuite',police_advanced:'Recherche avancée gratuite',arena_of_doom:'Arène du destin — essais gratuits',arena_store:'Achats dans la boutique de l’arène',vip_store:'Achats dans la boutique VIP'},
    de:{alliance_help:'Allianzmitglieder helfen',resource_challenge:'Sammel-Herausforderung wählen',radar:'Radarstation',zombie:'Rebellen / Zombies angreifen',gathering:'Ressourcen sammeln',daily_missions:'Tägliche Missionen',training:'Truppen und Beschleunigung',refinery:'Gewöhnliches Erz raffinieren',alliance_gifts:'Allianzgeschenke',mail_rewards:'Post-Belohnungen',vip_daily_gift:'Tägliche VIP-Truhe',alliance_technology:'Markierte Allianztechnologie',territory_rewards:'Gebietsbelohnungen',event_rewards:'Gratis- und Eventbelohnungen',police_normal:'Normale Gratissuche',police_advanced:'Erweiterte Gratissuche',arena_of_doom:'Arena des Untergangs — gratis',arena_store:'Im Arena-Laden kaufen',vip_store:'Im VIP-Laden kaufen'},
    it:{alliance_help:'Aiuta i membri dell’alleanza',resource_challenge:'Scegli la sfida raccolta',radar:'Stazione radar',zombie:'Attacca ribelli / zombie',gathering:'Raccogli risorse',daily_missions:'Missioni giornaliere',training:'Addestramento e accelerazione',refinery:'Raffina minerale comune',alliance_gifts:'Regali dell’alleanza',mail_rewards:'Ricompense posta',vip_daily_gift:'Forziere VIP giornaliero',alliance_technology:'Tecnologia alleanza marcata',territory_rewards:'Ricompense territorio',event_rewards:'Ricompense gratis ed eventi',police_normal:'Ricerca normale gratuita',police_advanced:'Ricerca avanzata gratuita',arena_of_doom:'Arena del destino — tentativi gratis',arena_store:'Acquista nel negozio Arena',vip_store:'Acquista nel negozio VIP'},
    es:{alliance_help:'Ayudar a miembros de la alianza',resource_challenge:'Elegir desafío de recolección',radar:'Estación de radar',zombie:'Atacar rebeldes / zombis',gathering:'Recolectar recursos',daily_missions:'Misiones diarias',training:'Entrenamiento y aceleración',refinery:'Refinar mineral común',alliance_gifts:'Regalos de alianza',mail_rewards:'Recompensas del correo',vip_daily_gift:'Cofre VIP diario',alliance_technology:'Tecnología de alianza marcada',territory_rewards:'Recompensas de territorio',event_rewards:'Recompensas gratis y eventos',police_normal:'Búsqueda normal gratuita',police_advanced:'Búsqueda avanzada gratuita',arena_of_doom:'Arena del Juicio — intentos gratis',arena_store:'Comprar en Tienda de Arena',vip_store:'Comprar en Tienda VIP'},
    pt:{alliance_help:'Ajudar membros da aliança',resource_challenge:'Escolher desafio de coleta',radar:'Estação de radar',zombie:'Atacar rebeldes / zumbis',gathering:'Coletar recursos',daily_missions:'Missões diárias',training:'Treino e aceleração',refinery:'Refinar minério comum',alliance_gifts:'Presentes da aliança',mail_rewards:'Recompensas do correio',vip_daily_gift:'Baú VIP diário',alliance_technology:'Tecnologia marcada da aliança',territory_rewards:'Recompensas de território',event_rewards:'Recompensas grátis e eventos',police_normal:'Busca normal grátis',police_advanced:'Busca avançada grátis',arena_of_doom:'Arena do Juízo — tentativas grátis',arena_store:'Comprar na Loja da Arena',vip_store:'Comprar na Loja VIP'},
    ru:{alliance_help:'Помощь членам альянса',resource_challenge:'Выбрать испытание сбора',radar:'Радарная станция',zombie:'Атаковать повстанцев / зомби',gathering:'Собирать ресурсы',daily_missions:'Ежедневные задания',training:'Обучение и ускорение',refinery:'Переработать обычную руду',alliance_gifts:'Подарки альянса',mail_rewards:'Награды почты',vip_daily_gift:'Ежедневный VIP-сундук',alliance_technology:'Отмеченная технология альянса',territory_rewards:'Награды территории',event_rewards:'Бесплатные награды и события',police_normal:'Обычный бесплатный поиск',police_advanced:'Продвинутый бесплатный поиск',arena_of_doom:'Арена рока — бесплатные попытки',arena_store:'Покупки в магазине арены',vip_store:'Покупки в VIP-магазине'}
  };
  Object.assign(FEATURE_OTHER,{
    'zh-cn':{resource_challenge:'选择资源挑战',radar:'雷达站',zombie:'攻击叛军 / 丧尸',gathering:'采集资源',daily_missions:'每日任务 Auto Complete',training:'训练士兵和加速任务',refinery:'精炼普通矿石',alliance_gifts:'联盟礼物',mail_rewards:'邮件奖励',vip_daily_gift:'每日 VIP 宝箱',alliance_technology:'捐献标记的联盟科技',territory_rewards:'领地奖励',event_rewards:'免费与活动奖励',police_normal:'警察局普通免费搜索',police_advanced:'警察局高级免费搜索',arena_of_doom:'末日竞技场 — 免费次数',arena_store:'购买竞技场商店中所有可用的已选商品',vip_store:'购买 VIP 商店中所有可用的已选商品',mysterious_merchant:'神秘商人 — 用资源购买全部可用商品并使用全部免费刷新'},
    'zh-tw':{resource_challenge:'選擇資源挑戰',radar:'雷達站',zombie:'攻擊叛軍 / 喪屍',gathering:'採集資源',daily_missions:'每日任務 Auto Complete',training:'訓練士兵和加速任務',refinery:'精煉普通礦石',alliance_gifts:'聯盟禮物',mail_rewards:'郵件獎勵',vip_daily_gift:'每日 VIP 寶箱',alliance_technology:'捐獻標記的聯盟科技',territory_rewards:'領地獎勵',event_rewards:'免費與活動獎勵',police_normal:'警察局普通免費搜尋',police_advanced:'警察局進階免費搜尋',arena_of_doom:'末日競技場 — 免費次數',arena_store:'購買競技場商店中所有可用的已選商品',vip_store:'購買 VIP 商店中所有可用的已選商品',mysterious_merchant:'神秘商人 — 用資源購買全部可用商品並使用全部免費刷新'},
    id:{resource_challenge:'Pilih tantangan sumber daya',radar:'Stasiun Radar',zombie:'Serang pemberontak / zombie',gathering:'Kumpulkan sumber daya',daily_missions:'Misi Harian Auto Complete',training:'Latih pasukan dan tugas percepatan',refinery:'Murnikan Bijih Biasa',alliance_gifts:'Hadiah aliansi',mail_rewards:'Hadiah surat',vip_daily_gift:'Peti VIP harian',alliance_technology:'Donasi teknologi aliansi bertanda',territory_rewards:'Hadiah wilayah',event_rewards:'Hadiah gratis dan event',police_normal:'Pencarian normal gratis Polisi',police_advanced:'Pencarian lanjutan gratis Polisi',arena_of_doom:'Arena of Doom — percobaan gratis',arena_store:'Beli semua barang Arena terpilih yang tersedia',vip_store:'Beli semua barang VIP terpilih yang tersedia',mysterious_merchant:'Pedagang Misterius — beli semua dengan sumber daya dan gunakan semua refresh gratis'},
    th:{resource_challenge:'เลือกภารกิจทรัพยากร',radar:'สถานีเรดาร์',zombie:'โจมตีกบฏ / ซอมบี้',gathering:'รวบรวมทรัพยากร',daily_missions:'ภารกิจรายวัน Auto Complete',training:'ฝึกทหารและภารกิจเร่งเวลา',refinery:'กลั่นแร่ทั่วไป',alliance_gifts:'ของขวัญพันธมิตร',mail_rewards:'รางวัลจดหมาย',vip_daily_gift:'หีบ VIP รายวัน',alliance_technology:'บริจาคเทคโนโลยีพันธมิตรที่ทำเครื่องหมาย',territory_rewards:'รางวัลอาณาเขต',event_rewards:'รางวัลฟรีและกิจกรรม',police_normal:'ค้นหาปกติฟรีของสถานีตำรวจ',police_advanced:'ค้นหาขั้นสูงฟรีของสถานีตำรวจ',arena_of_doom:'Arena of Doom — ครั้งฟรี',arena_store:'ซื้อสินค้าที่เลือกและมีอยู่ทั้งหมดจากร้านอารีนา',vip_store:'ซื้อสินค้าที่เลือกและมีอยู่ทั้งหมดจากร้าน VIP',mysterious_merchant:'พ่อค้าลึกลับ — ซื้อทุกอย่างที่มีด้วยทรัพยากรและใช้รีเฟรชฟรีทั้งหมด'},
    tr:{resource_challenge:'Kaynak mücadelesini seç',radar:'Radar İstasyonu',zombie:'Asi / zombilere saldır',gathering:'Kaynak topla',daily_missions:'Günlük Görevler Auto Complete',training:'Birlik eğitimi ve hızlandırma görevi',refinery:'Sıradan Cevheri rafine et',alliance_gifts:'İttifak hediyeleri',mail_rewards:'Posta ödülleri',vip_daily_gift:'Günlük VIP sandığı',alliance_technology:'İşaretli ittifak teknolojisine bağış',territory_rewards:'Bölge ödülleri',event_rewards:'Ücretsiz ve etkinlik ödülleri',police_normal:'Polis normal ücretsiz arama',police_advanced:'Polis gelişmiş ücretsiz arama',arena_of_doom:'Doom Arenası — ücretsiz haklar',arena_store:'Seçili mevcut tüm Arena ürünlerini satın al',vip_store:'Seçili mevcut tüm VIP ürünlerini satın al',mysterious_merchant:'Gizemli Tüccar — kaynakla mevcut her şeyi al ve tüm ücretsiz yenilemeleri kullan'},
    ko:{resource_challenge:'자원 도전 선택',radar:'레이더 기지',zombie:'반란군 / 좀비 공격',gathering:'자원 채집',daily_missions:'일일 임무 Auto Complete',training:'병력 훈련 및 가속 임무',refinery:'일반 광석 정제',alliance_gifts:'연맹 선물',mail_rewards:'우편 보상',vip_daily_gift:'일일 VIP 상자',alliance_technology:'표시된 연맹 기술 기부',territory_rewards:'영토 보상',event_rewards:'무료 및 이벤트 보상',police_normal:'경찰서 일반 무료 탐색',police_advanced:'경찰서 고급 무료 탐색',arena_of_doom:'파멸의 아레나 — 무료 횟수',arena_store:'선택한 아레나 상품 중 구매 가능한 모든 상품 구매',vip_store:'선택한 VIP 상품 중 구매 가능한 모든 상품 구매',mysterious_merchant:'신비한 상인 — 자원으로 가능한 모든 상품 구매 및 무료 갱신 모두 사용'},
    ja:{resource_challenge:'資源チャレンジを選択',radar:'レーダーステーション',zombie:'反乱軍 / ゾンビを攻撃',gathering:'資源採集',daily_missions:'デイリーミッション Auto Complete',training:'兵士訓練と加速タスク',refinery:'一般鉱石を精製',alliance_gifts:'同盟ギフト',mail_rewards:'メール報酬',vip_daily_gift:'デイリー VIP 宝箱',alliance_technology:'指定された同盟技術に寄付',territory_rewards:'領地報酬',event_rewards:'無料・イベント報酬',police_normal:'警察署の通常無料捜索',police_advanced:'警察署の上級無料捜索',arena_of_doom:'終末アリーナ — 無料回数',arena_store:'選択したアリーナ商品の購入可能分をすべて購入',vip_store:'選択した VIP 商品の購入可能分をすべて購入',mysterious_merchant:'謎の商人 — 資源で購入可能な商品をすべて買い、無料更新をすべて使用'},
    vi:{resource_challenge:'Chọn thử thách tài nguyên',radar:'Trạm Radar',zombie:'Tấn công phiến quân / zombie',gathering:'Thu thập tài nguyên',daily_missions:'Nhiệm vụ hằng ngày Auto Complete',training:'Huấn luyện quân và nhiệm vụ tăng tốc',refinery:'Tinh luyện Quặng Thường',alliance_gifts:'Quà liên minh',mail_rewards:'Phần thưởng thư',vip_daily_gift:'Rương VIP hằng ngày',alliance_technology:'Quyên góp công nghệ liên minh được đánh dấu',territory_rewards:'Phần thưởng lãnh thổ',event_rewards:'Phần thưởng miễn phí và sự kiện',police_normal:'Tìm kiếm thường miễn phí của Cảnh sát',police_advanced:'Tìm kiếm nâng cao miễn phí của Cảnh sát',arena_of_doom:'Đấu trường Tận thế — lượt miễn phí',arena_store:'Mua toàn bộ vật phẩm Đấu trường đã chọn và đang có',vip_store:'Mua toàn bộ vật phẩm VIP đã chọn và đang có',mysterious_merchant:'Thương nhân Bí ẩn — mua mọi thứ có thể bằng tài nguyên và dùng mọi lượt làm mới miễn phí'}
  });
  Object.assign(FEATURE_OTHER.fr,{arena_store:'Acheter tout ce qui est disponible parmi les objets choisis de l’arène',vip_store:'Acheter tout ce qui est disponible parmi les objets VIP choisis'});
  Object.assign(FEATURE_OTHER.de,{arena_store:'Alle verfügbaren ausgewählten Arena-Artikel kaufen',vip_store:'Alle verfügbaren ausgewählten VIP-Artikel kaufen'});
  Object.assign(FEATURE_OTHER.it,{arena_store:'Acquista tutti gli oggetti Arena selezionati disponibili',vip_store:'Acquista tutti gli oggetti VIP selezionati disponibili'});
  Object.assign(FEATURE_OTHER.es,{arena_store:'Comprar todo lo disponible de los objetos de Arena elegidos',vip_store:'Comprar todo lo disponible de los objetos VIP elegidos'});
  Object.assign(FEATURE_OTHER.pt,{arena_store:'Comprar tudo disponível dos itens de Arena selecionados',vip_store:'Comprar tudo disponível dos itens VIP selecionados'});
  Object.assign(FEATURE_OTHER.ru,{arena_store:'Купить все доступные выбранные товары арены',vip_store:'Купить все доступные выбранные VIP-товары'});
  Object.assign(FEATURE_OTHER.fr,{mysterious_merchant:'Marchand mystérieux — tout acheter avec des ressources et actualisations gratuites'});
  Object.assign(FEATURE_OTHER.de,{mysterious_merchant:'Mysteriöser Händler — alles mit Ressourcen und Gratis-Aktualisierungen kaufen'});
  Object.assign(FEATURE_OTHER.it,{mysterious_merchant:'Mercante misterioso — compra tutto con risorse e aggiornamenti gratuiti'});
  Object.assign(FEATURE_OTHER.es,{mysterious_merchant:'Mercader misterioso — comprar todo con recursos y actualizaciones gratis'});
  Object.assign(FEATURE_OTHER.pt,{mysterious_merchant:'Mercador misterioso — comprar tudo com recursos e atualizações grátis'});
  Object.assign(FEATURE_OTHER.ru,{mysterious_merchant:'Таинственный торговец — купить всё за ресурсы и использовать бесплатные обновления'});
  Object.keys(FEATURE_OTHER).forEach(function(lang){delete FEATURE_OTHER[lang].alliance_help;});
  var FEATURE_GROUPS = [
    ['resource_challenge','radar','zombie','gathering','daily_missions','training','refinery'],
    ['alliance_gifts','mail_rewards','vip_daily_gift','alliance_technology','territory_rewards','event_rewards'],
    ['police_normal','police_advanced','arena_of_doom','arena_store','vip_store','mysterious_merchant']
  ];
  var FEATURE_MASK_KEYS = ['resource_challenge','radar','zombie','gathering','daily_missions','training','refinery',null,'alliance_gifts','mail_rewards','vip_daily_gift','alliance_technology','territory_rewards','event_rewards','police_normal','police_advanced','arena_of_doom','arena_store','vip_store','mysterious_merchant'];
  var DEFAULT_FEATURES = {};
  FEATURE_GROUPS.forEach(function (group) { group.forEach(function (key) { DEFAULT_FEATURES[key] = !['police_normal','police_advanced','arena_of_doom','arena_store','vip_store'].includes(key); }); });
  var STATIC_CATALOG = {
    arena:[
      [91030,'60m Training Speedup',1,21,750,0],[91031,'Advanced Search Map',1,21,9000,0],[91032,'Random Resource Pack III',1,21,15,0],[91033,'Intermediate Resource Pack',1,21,360,0],[91034,'Extermination Card',2,21,1000,0],[91035,'Battle Manual (5,000 EXP)',10,21,2500,0],[91036,'Defensive Fabric',300,21,4500,0],[91037,'Carbon Steel',10,21,1500,0],[91038,'Carbon Steel',60,21,9000,1001],[91039,'Shoes Fragment Choice Box',3,21,3000,0],[91040,'Pants Fragment Choice Box',3,21,3750,1002],[91041,'Honing Chip',1,21,2250,1003],[91042,'Shoes Fragment Choice Box',1,21,8500,1004],[91043,'Pants Fragment Choice Box',1,21,10600,1005],[91044,'Superb Shoes Fragment Choice Box',1,21,32000,1006],[91045,'Superb Pants Fragment Choice Box',1,21,40000,1007]
    ],
    vip:[
      [20010,'Stamina Recovery I',1,4,12000,1],[20011,'5m Speedup',1,3,4000,1],[20030,'Elite Hero Badge S',1,4,59000,3],[20032,'Beast Fragment Random Pod',1,3,200000,3],[20033,'Elite Beast Stim',1,4,375000,3],[20080,'Legendary Hero Badge S',1,3,450000,8],[20105,'High-Performance Motor Fragment',1,5,250000,10]
    ]
  };
  Object.keys(STATIC_CATALOG).forEach(function(shop){STATIC_CATALOG[shop]=STATIC_CATALOG[shop].map(function(x){return {item_id:x[0],name:x[1],quantity:x[2],currency_subtype:x[3],price:x[4],unlock_level:x[5]};});});
  var ITEM_IDS=[91030,91031,91032,91033,91034,91035,91036,91037,91038,91039,91040,91041,91042,91043,91044,91045,20010,20011,20030,20032,20033,20080,20105];
  var ITEM_NAMES={
    ar:['تسريع تدريب 60 دقيقة','خريطة بحث متقدمة','حزمة موارد عشوائية III','حزمة موارد متوسطة','بطاقة إبادة','دليل قتال (5000 خبرة)','نسيج دفاعي','فولاذ كربوني','فولاذ كربوني','صندوق اختيار أجزاء الحذاء','صندوق اختيار أجزاء البنطال','شريحة صقل','صندوق اختيار أجزاء الحذاء','صندوق اختيار أجزاء البنطال','صندوق أجزاء حذاء فائق','صندوق أجزاء بنطال فائق','استعادة طاقة I','تسريع 5 دقائق','شارة بطل نخبة S','حاوية أجزاء وحش عشوائية','منشط وحش نخبة','شارة بطل أسطوري S','جزء محرك عالي الأداء'],
    fr:['Accélération entraînement 60 min','Carte de recherche avancée','Pack de ressources aléatoire III','Pack de ressources intermédiaire','Carte d’extermination','Manuel de combat (5 000 EXP)','Tissu défensif','Acier au carbone','Acier au carbone','Coffre de fragments de chaussures','Coffre de fragments de pantalon','Puce de polissage','Coffre de fragments de chaussures','Coffre de fragments de pantalon','Coffre de chaussures superbe','Coffre de pantalon superbe','Récupération d’endurance I','Accélération 5 min','Insigne de héros élite S','Capsule aléatoire de fragments de bête','Stimulant de bête élite','Insigne de héros légendaire S','Fragment de moteur haute performance'],
    de:['Trainingsbeschleunigung 60 Min.','Erweiterte Suchkarte','Zufälliges Ressourcenpaket III','Mittleres Ressourcenpaket','Vernichtungskarte','Kampfhandbuch (5.000 EP)','Verteidigungsstoff','Kohlenstoffstahl','Kohlenstoffstahl','Schuhfragment-Auswahlkiste','Hosenfragment-Auswahlkiste','Polierchip','Schuhfragment-Auswahlkiste','Hosenfragment-Auswahlkiste','Erstklassige Schuhfragmentkiste','Erstklassige Hosenfragmentkiste','Ausdauerwiederherstellung I','Beschleunigung 5 Min.','Elite-Heldenabzeichen S','Zufällige Bestienfragment-Kapsel','Elite-Bestien-Stimulans','Legendäres Heldenabzeichen S','Hochleistungsmotor-Fragment'],
    it:['Accelerazione addestramento 60 min','Mappa ricerca avanzata','Pacco risorse casuale III','Pacco risorse intermedio','Carta sterminio','Manuale di battaglia (5.000 ESP)','Tessuto difensivo','Acciaio al carbonio','Acciaio al carbonio','Cassa scelta frammenti scarpe','Cassa scelta frammenti pantaloni','Chip di levigatura','Cassa scelta frammenti scarpe','Cassa scelta frammenti pantaloni','Cassa frammenti scarpe superba','Cassa frammenti pantaloni superba','Recupero resistenza I','Accelerazione 5 min','Distintivo eroe élite S','Capsula casuale frammenti bestia','Stimolante bestia élite','Distintivo eroe leggendario S','Frammento motore ad alte prestazioni'],
    es:['Aceleración de entrenamiento 60 min','Mapa de búsqueda avanzada','Paquete aleatorio de recursos III','Paquete intermedio de recursos','Tarjeta de exterminio','Manual de batalla (5.000 EXP)','Tejido defensivo','Acero al carbono','Acero al carbono','Caja de fragmentos de calzado','Caja de fragmentos de pantalón','Chip de pulido','Caja de fragmentos de calzado','Caja de fragmentos de pantalón','Caja superior de calzado','Caja superior de pantalón','Recuperación de aguante I','Aceleración 5 min','Insignia de héroe élite S','Cápsula aleatoria de fragmentos de bestia','Estimulante de bestia élite','Insignia de héroe legendario S','Fragmento de motor de alto rendimiento'],
    pt:['Aceleração de treino 60 min','Mapa de busca avançada','Pacote aleatório de recursos III','Pacote intermediário de recursos','Cartão de extermínio','Manual de batalha (5.000 EXP)','Tecido defensivo','Aço carbono','Aço carbono','Caixa de fragmentos de calçados','Caixa de fragmentos de calças','Chip de polimento','Caixa de fragmentos de calçados','Caixa de fragmentos de calças','Caixa superior de calçados','Caixa superior de calças','Recuperação de vigor I','Aceleração 5 min','Insígnia de herói elite S','Cápsula aleatória de fragmentos de fera','Estimulante de fera elite','Insígnia de herói lendário S','Fragmento de motor de alto desempenho'],
    ru:['Ускорение обучения 60 мин.','Продвинутая карта поиска','Случайный набор ресурсов III','Средний набор ресурсов','Карта истребления','Боевой справочник (5 000 опыта)','Защитная ткань','Углеродистая сталь','Углеродистая сталь','Ящик фрагментов обуви','Ящик фрагментов брюк','Чип шлифовки','Ящик фрагментов обуви','Ящик фрагментов брюк','Превосходный ящик обуви','Превосходный ящик брюк','Восстановление выносливости I','Ускорение 5 мин.','Знак элитного героя S','Случайная капсула фрагментов зверя','Стимулятор элитного зверя','Знак легендарного героя S','Фрагмент высокопроизводительного двигателя']
  };

  async function decodeData() {
    try {
      var raw = new URLSearchParams(location.search).get('data');
      if (!raw) { return null; }
      var compressed = raw.indexOf('z.') === 0;
      if (compressed) { raw = raw.slice(2); }
      raw = raw.replace(/-/g, '+').replace(/_/g, '/');
      while (raw.length % 4) { raw += '='; }
      var binary = atob(raw);
      if (!compressed) {
        return JSON.parse(decodeURIComponent(Array.prototype.map.call(binary, function (c) { return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2); }).join('')));
      }
      if (typeof DecompressionStream !== 'function') { return null; }
      var bytes = Uint8Array.from(binary, function(c){return c.charCodeAt(0);});
      var stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate'));
      var decoded = await new Response(stream).arrayBuffer();
      return JSON.parse(new TextDecoder().decode(decoded));
    } catch (_) { return null; }
  }
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function normalizeUiLanguage(value) {
    var language=String(value||'en').trim().toLowerCase().replace(/_/g,'-');
    var chinese={'zh':'zh-cn','zh-cn':'zh-cn','zh-sg':'zh-cn','zh-hans':'zh-cn','zh-tw':'zh-tw','zh-hk':'zh-tw','zh-mo':'zh-tw','zh-hant':'zh-tw'};
    language=chinese[language]||language.split('-',1)[0];
    return LANGS.some(function(x){return x[0]===language;})?language:'en';
  }
  var payload = await decodeData();
  var state = {farms:[], catalog:STATIC_CATALOG, lang:'en', kingdom:0, owner:0, adminEdit:false, adminFarmId:'', screen:'home', current:null, editorTab:null, copyMode:null, source:null, targets:{}, transferTargets:{}, transferTarget:'', transferAmounts:{food:0,wood:0,steel:0,oil:0}, search:''};
  if (payload && (Array.isArray(payload.farms) || Array.isArray(payload.f))) {
    state.lang = normalizeUiLanguage(localStorage.getItem('doomsday-lang') || payload.language || payload.l || 'en');
    state.kingdom = Number(payload.kingdom_id || payload.k || 0);
    state.owner = Number(payload.owner_telegram_id || payload.o || payload.telegram_id || payload.t || 0);
    state.adminEdit = Number(payload.admin_edit || payload.a || 0) === 1;
    state.adminFarmId = String(payload.admin_farm_id || payload.x || '');
    state.catalog = payload.shop_catalog || state.catalog;
    var rawFarms = payload.farms || payload.f.map(function(row){
      var featureKeys=FEATURE_GROUPS.reduce(function(a,b){return a.concat(b);},[]), features={};
      FEATURE_MASK_KEYS.forEach(function(key,index){if(featureKeys.indexOf(key)!==-1){features[key]=!!(Number(row[6]) & Math.pow(2,index));}});
      return {id:row[0],castle_name:row[1],login:row[2],on_off:row[3],resources:{food:row[4][0],wood:row[4][1],steel:row[4][2],oil:row[4][3]},zombie:{max_level:row[5][0],min_level:row[5][1],multiplier:String(row[5][2])},features:features,shops:{arena:row[7]||[],vip:row[8]||[]},resource_snapshot:Array.isArray(row[9])?{food:row[9][0],wood:row[9][1],steel:row[9][2],oil:row[9][3]}:null,resource_snapshot_at:Number(row[10]||0)};
    });
    state.farms = rawFarms.map(function (farm) {
      var features = Object.assign({}, DEFAULT_FEATURES, farm.features || {});
      return {
        id:String(farm.id), castle_name:String(farm.castle_name || ('farm-' + farm.id)), login:String(farm.login || ''), password:'', on_off:farm.on_off ? 1 : 0,
        resources:Object.assign({food:0,wood:0,steel:0,oil:0}, farm.resources || {}),
        zombie:Object.assign({max_level:40,min_level:35,multiplier:'auto'}, farm.zombie || {}),
        features:features, shops:Object.assign({arena:[],vip:[]}, farm.shops || {}), resource_snapshot:farm.resource_snapshot, resource_snapshot_at:Number(farm.resource_snapshot_at||0)
      };
    });
    if(state.adminEdit){state.farms=state.farms.filter(function(farm){return farm.id===state.adminFarmId;});}
    if(!Number.isInteger(state.kingdom)||state.kingdom<=0||(state.adminEdit&&state.farms.length!==1)){payload=null;state.farms=[];}
  }

  var home = document.getElementById('homeScreen'), editor = document.getElementById('editorScreen'), language = document.getElementById('languageScreen'), transfer=document.getElementById('transferScreen');
  var saveBtn = document.getElementById('saveBtn'), message = document.getElementById('message'), backBtn = document.getElementById('backBtn');
  function tr(key) { return (OV[state.lang] && OV[state.lang][key]) || (TRANSFER_OV[state.lang] && TRANSFER_OV[state.lang][key]) || (REGION_OV[state.lang] && REGION_OV[state.lang][key]) || EN[key] || key; }
  function featureName(key) { return state.lang === 'ar' ? FEATURE_AR[key] : ((FEATURE_OTHER[state.lang] && FEATURE_OTHER[state.lang][key]) || FEATURE_EN[key]); }
  function itemName(item) { var index=ITEM_IDS.indexOf(Number(item.item_id)), names=ITEM_NAMES[state.lang]; return index>=0&&names ? names[index] : item.name; }
  function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];}); }
  function setMessage(text, kind) { message.textContent = text || ''; message.className = kind || ''; }
  function total(farm) { return ['food','wood','steel','oil'].reduce(function (n,k) { return n + Number(farm.resources[k] || 0); },0); }
  function compactAmount(value){value=Number(value||0);if(value>=1000000000){return (value/1000000000).toFixed(value>=10000000000?1:2).replace(/\.0+$/,'')+'B';}if(value>=1000000){return (value/1000000).toFixed(value>=10000000?1:2).replace(/\.0+$/,'')+'M';}if(value>=1000){return (value/1000).toFixed(value>=10000?1:2).replace(/\.0+$/,'')+'K';}return String(Math.max(0,Math.floor(value)));}
  function stockHtml(farm){var s=farm.resource_snapshot;if(!s||['food','wood','steel','oil'].some(function(k){return s[k]===null||s[k]===undefined;})){return '<div class="stock-unavailable">'+esc(tr('stockUnavailable'))+'</div>';}return '<div class="stock-grid">'+['food','wood','steel','oil'].map(function(k){return '<span><small>'+esc(tr(k))+'</small><b>'+compactAmount(s[k])+'</b></span>';}).join('')+'</div>';}
  function stockTimeHtml(farm){if(!farm.resource_snapshot_at){return '';}var date=new Date(farm.resource_snapshot_at*1000);return '<div class="stock-time">'+esc(tr('stockUpdated'))+': '+esc(date.toLocaleString(state.lang))+'</div>';}
  function hasProtectedAccess(){return false;}
  function requireProtectedAccess(){if(hasProtectedAccess()){return true;}var notice=tr('notAuthorized');setMessage(notice,'error');if(tg&&typeof tg.showAlert==='function'&&(!tg.isVersionAtLeast||tg.isVersionAtLeast('6.2'))){try{tg.showAlert(notice);}catch(_){}}return false;}
  function isEditorTabAllowed(tab){return tab==='identity'||tab==='gathering';}
  function isEditorTabLocked(tab){return !isEditorTabAllowed(tab);}
  function primaryTabsHtml(active){var locked=!hasProtectedAccess();return '<nav class="screen-tabs" aria-label="'+esc(tr('title'))+'"><button class="screen-tab '+(active==='castles'?'active':'')+'" type="button" data-primary-tab="castles">🏰 '+esc(tr('castlesTab'))+'</button><button class="screen-tab '+(active==='transfer'?'active ':'')+(locked?'locked':'')+'" type="button" data-primary-tab="transfer" aria-disabled="'+String(locked)+'">'+(locked?'🔒 ':'📦 ')+esc(tr('sendTransfer'))+'</button></nav>';}
  function bindPrimaryTabs(root){root.querySelectorAll('[data-primary-tab]').forEach(function(button){button.onclick=function(){if(button.dataset.primaryTab==='castles'){renderHome();return;}if(requireProtectedAccess()){renderTransfer();}};});}
  function direction() { var rtl = state.lang === 'ar'; document.documentElement.dir = rtl ? 'rtl' : 'ltr'; document.documentElement.lang = state.lang; document.body.dataset.lang = state.lang; }

  function renderLanguage() {
    state.screen = 'language'; direction(); home.hidden = editor.hidden = transfer.hidden = true; language.hidden = false; backBtn.hidden = false; saveBtn.parentElement.hidden = false; saveBtn.disabled = false;
    saveBtn.textContent = '🌐 ' + (LANGUAGE_CONFIRM_TEXT[state.lang] || LANGUAGE_CONFIRM_TEXT.en);
    language.innerHTML = '<h2 class="section-title"><span>🌐</span>'+esc(tr('language'))+'</h2><div class="languages">'+LANGS.map(function(x){var selected=x[0]===state.lang;return '<button class="language '+(selected?'active':'')+'" type="button" data-lang="'+x[0]+'" aria-pressed="'+String(selected)+'">'+x[1]+' '+esc(x[2])+'</button>';}).join('')+'</div>';
    language.querySelectorAll('[data-lang]').forEach(function(btn){btn.onclick=function(){state.lang=btn.dataset.lang;localStorage.setItem('doomsday-lang',state.lang);renderLanguage();};});
  }

  function renderHome() {
    state.screen = 'home'; state.current = null; state.editorTab=null; direction(); language.hidden = editor.hidden = transfer.hidden = true; home.hidden = false; backBtn.hidden = true; saveBtn.parentElement.hidden = false;
    document.getElementById('eyebrow').textContent = tr('eyebrow'); document.getElementById('title').textContent = tr('title'); saveBtn.textContent = '💾 ' + tr('save');
    var rows = state.farms.filter(function(f){var q=state.search.toLowerCase();return !q || f.id.toLowerCase().includes(q) || f.castle_name.toLowerCase().includes(q);});
    var helper = state.copyMode ? '<div class="copy-panel">'+esc(state.copyMode==='source'?tr('chooseSource'):tr('chooseTargets'))+(state.source?' <b>'+esc(tr('source'))+': '+esc(state.source.castle_name)+'</b>':'')+'</div>' : '';
    home.innerHTML = '<div class="hero"><div class="region-badge">'+esc(tr('region'))+' · K'+esc(state.kingdom)+'</div><h2>'+esc(tr('title'))+'</h2><p>'+esc(tr('subtitle'))+' · '+esc(tr('telegram'))+' '+esc(payload ? (payload.telegram_id || payload.t) : '—')+'</p></div>'+primaryTabsHtml('castles')+
      '<div class="toolbar"><input id="search" class="field" value="'+esc(state.search)+'" placeholder="'+esc(tr('search'))+'"><button id="copyBtn" class="small-btn '+(state.copyMode?'active':'')+'">'+esc(state.copyMode?tr('cancel'):tr('copy'))+'</button>'+(state.copyMode==='targets'?'<button id="applyBtn" class="small-btn">'+esc(tr('apply'))+'</button>':'')+'</div>'+helper+
      '<div class="castle-list">'+(rows.length?rows.map(castleCard).join(''):'<div class="empty">🏚️<br>'+esc(payload?tr('noFarms'):tr('openTelegram'))+'</div>')+'</div>';
    bindPrimaryTabs(home);
    document.getElementById('search').oninput=function(){
      state.search=this.value;
      var q=state.search.toLowerCase();
      home.querySelectorAll('[data-farm]').forEach(function(card){
        var farm=state.farms.find(function(f){return f.id===card.dataset.farm;});
        card.hidden=!!q && !farm.id.toLowerCase().includes(q) && !farm.castle_name.toLowerCase().includes(q);
      });
    };
    document.getElementById('copyBtn').onclick=function(){state.copyMode=state.copyMode?null:'source';state.source=null;state.targets={};renderHome();};
    var apply=document.getElementById('applyBtn'); if(apply){apply.onclick=applyCopy;}
    home.querySelectorAll('[data-farm]').forEach(function(card){card.onclick=function(e){var farm=state.farms.find(function(f){return f.id===card.dataset.farm;});if(e.target.matches('input')){e.stopPropagation();}selectCastle(farm);};});
  }
  function castleCard(farm) {
    var checked = state.targets[farm.id] ? ' checked' : '';
    var pick = state.copyMode==='targets' ? '<input class="pick" type="checkbox" aria-label="target"'+checked+'>' : (state.copyMode==='source'?'<input class="pick" type="radio" name="source">':'');
    return '<article class="castle-card" data-farm="'+esc(farm.id)+'"><div class="castle-icon">🏰</div><div><div class="castle-name">'+esc(farm.castle_name)+'</div><div class="castle-id">ID '+esc(farm.id)+' · K'+esc(state.kingdom)+'</div></div><div>'+pick+'<div class="status '+(farm.on_off?'on':'off')+'">'+esc(farm.on_off?tr('on'):tr('off'))+'</div></div><div class="castle-stock"><div class="stock-label">'+esc(tr('ordinaryResources'))+'</div>'+stockHtml(farm)+stockTimeHtml(farm)+'</div></article>';
  }
  function selectCastle(farm) {
    if (state.copyMode==='source') { state.source=farm;state.copyMode='targets';renderHome();return; }
    if (state.copyMode==='targets') { if(state.source&&farm.id===state.source.id){return;}state.targets[farm.id]=!state.targets[farm.id];renderHome();return; }
    state.current=farm;state.editorTab=null;renderEditor();
  }
  function applyCopy() {
    var ids=Object.keys(state.targets).filter(function(id){return state.targets[id];}); if(!ids.length){setMessage(tr('selectTarget'),'error');return;}
    ids.forEach(function(id){var farm=state.farms.find(function(f){return f.id===id;});farm.resources=clone(state.source.resources);farm.features.gathering=!!state.source.features.gathering;});
    state.copyMode=null;state.targets={};setMessage(tr('copied'),'success');renderHome();
  }

  function selectedTransferFarms(){return Object.keys(state.transferTargets).filter(function(id){return state.transferTargets[id];});}
  function fireSwitch(attributes,checked){return '<span class="fire-switch"><input '+attributes+(checked?' checked':'')+'><span class="switch-track" aria-hidden="true"><span class="switch-knob"></span></span></span>';}
  function renderTransfer(){
    if(!requireProtectedAccess()){return;}
    state.screen='transfer';direction();home.hidden=editor.hidden=language.hidden=true;transfer.hidden=false;backBtn.hidden=false;saveBtn.parentElement.hidden=true;
    document.getElementById('eyebrow').textContent=tr('transfer');document.getElementById('title').textContent=tr('sendTransfer');
    var ids=selectedTransferFarms();
    transfer.innerHTML=primaryTabsHtml('transfer')+'<div class="transfer-page-hero"><span class="transfer-page-icon">📦</span><div><div class="region-badge">'+esc(tr('region'))+' · K'+esc(state.kingdom)+'</div><h2>'+esc(tr('transfer'))+'</h2><p>'+esc(tr('aggregateHint'))+'</p></div></div>'+
      '<section class="section-card"><h3 class="section-title"><span>◆</span>'+esc(tr('transferTarget'))+'</h3><input id="transferTarget" class="field" inputmode="numeric" autocomplete="off" value="'+esc(state.transferTarget)+'" placeholder="'+esc(tr('transferTarget'))+'"></section>'+
      '<section class="section-card"><h3 class="section-title"><span>◎</span>'+esc(tr('enterAmounts'))+'</h3><p class="section-copy">'+esc(tr('aggregateAmounts'))+'</p><div class="transfer-amounts">'+['food','wood','steel','oil'].map(function(k){return '<label><span>'+esc(tr(k))+'</span><input class="field" data-transfer-amount="'+k+'" type="number" inputmode="numeric" min="0" max="1000000000000" step="1" value="'+Number(state.transferAmounts[k]||0)+'"></label>';}).join('')+'</div></section>'+
      '<section class="section-card"><div class="transfer-select-head"><h3 class="section-title"><span>🏰</span>'+esc(tr('selectedFarms'))+' <b id="transferCount">'+ids.length+'</b></h3><div><button id="selectAllFarms" class="mini-action" type="button">'+esc(tr('selectAll'))+'</button><button id="clearFarms" class="mini-action" type="button">'+esc(tr('clearAll'))+'</button></div></div><p class="section-copy">'+esc(tr('stockLimitNote'))+'</p><div class="transfer-farm-list">'+state.farms.map(function(farm){var selected=!!state.transferTargets[farm.id];return '<label class="transfer-farm-card"><span class="castle-icon">🏰</span><span class="transfer-farm-info"><b>'+esc(farm.castle_name)+'</b><small>ID '+esc(farm.id)+' · K'+esc(state.kingdom)+'</small>'+stockHtml(farm)+stockTimeHtml(farm)+'</span>'+fireSwitch('type="checkbox" data-transfer-farm="'+esc(farm.id)+'"',selected)+'</label>';}).join('')+'</div></section>'+
      '<section class="transfer-submit"><div><span>'+esc(tr('selectedFarms'))+'</span><b id="transferSubmitCount">'+ids.length+'</b></div><button id="confirmTransfer" class="gold-btn" type="button">'+esc(tr('confirmTransfer'))+'</button><div id="transferError" class="transfer-error" role="status"></div></section>';
    bindPrimaryTabs(transfer);
    document.getElementById('transferTarget').oninput=function(){state.transferTarget=this.value.replace(/\D/g,'').slice(0,20);this.value=state.transferTarget;};
    transfer.querySelectorAll('[data-transfer-amount]').forEach(function(input){input.oninput=function(){var value=Math.max(0,Math.min(1000000000000,Math.floor(Number(input.value)||0)));state.transferAmounts[input.dataset.transferAmount]=value;};});
    transfer.querySelectorAll('[data-transfer-farm]').forEach(function(input){input.onchange=function(){state.transferTargets[input.dataset.transferFarm]=input.checked;updateTransferCount();};});
    document.getElementById('selectAllFarms').onclick=function(){state.farms.forEach(function(farm){state.transferTargets[farm.id]=true;});renderTransfer();};
    document.getElementById('clearFarms').onclick=function(){state.transferTargets={};renderTransfer();};
    document.getElementById('confirmTransfer').onclick=confirmTransfer;
  }
  function updateTransferCount(){var count=selectedTransferFarms().length;document.getElementById('transferCount').textContent=count;document.getElementById('transferSubmitCount').textContent=count;}
  function requestId(){var bytes=new Uint32Array(2);if(window.crypto&&window.crypto.getRandomValues){window.crypto.getRandomValues(bytes);}else{bytes[0]=Math.floor(Math.random()*0xffffffff);bytes[1]=Math.floor(Math.random()*0xffffffff);}return 'tr_'+Date.now().toString(36)+'_'+bytes[0].toString(36)+bytes[1].toString(36);}
  function confirmTransfer(){
    var amounts={}, totalAmount=0;
    transfer.querySelectorAll('[data-transfer-amount]').forEach(function(input){var value=Math.max(0,Math.min(1000000000000,Math.floor(Number(input.value)||0)));amounts[input.dataset.transferAmount]=value;totalAmount+=value;});
    var ids=selectedTransferFarms(), target=String(state.transferTarget||'');
    if(!totalAmount||!ids.length||!/^\d+$/.test(target)||ids.includes(target)){document.getElementById('transferError').textContent=tr('transferInvalid');return;}
    if(!tg){document.getElementById('transferError').textContent=tr('openTelegram');return;}
    var button=document.getElementById('confirmTransfer');button.disabled=true;
    try{tg.sendData(JSON.stringify({action:'transfer_resources',request_id:requestId(),language:state.lang,kingdom_id:state.kingdom,owner_telegram_id:state.owner,target_player_id:target,farm_ids:ids,resources:amounts}));document.getElementById('transferError').className='transfer-error success';document.getElementById('transferError').textContent=tr('transferSent');}
    catch(_){button.disabled=false;document.getElementById('transferError').textContent=tr('invalid');}
  }

  function renderEditor() {
    var f=state.current;state.screen='editor';direction();home.hidden=language.hidden=transfer.hidden=true;editor.hidden=false;backBtn.hidden=false;saveBtn.parentElement.hidden=false;saveBtn.textContent='💾 '+tr('save');
    document.getElementById('title').textContent=f.castle_name;
    editor.innerHTML='<div class="editor-head"><div><h2>🏰 '+esc(f.castle_name)+'</h2><div class="castle-id">ID '+esc(f.id)+'</div></div><label class="power-control"><b id="powerLabel">'+esc(f.on_off?tr('on'):tr('off'))+'</b>'+fireSwitch('id="power" type="checkbox"',!!f.on_off)+'</label></div>'+
      editorTabsHtml()+(state.editorTab?editorTabHtml(f):'');
    document.getElementById('power').onchange=function(){var enabled=this.checked,previous=!!f.on_off;if(!sendFarmEnabled(f,enabled)){this.checked=previous;return;}f.on_off=enabled?1:0;document.getElementById('powerLabel').textContent=tr(enabled?'on':'off');};
    editor.querySelectorAll('[data-editor-tab]').forEach(function(button){button.onclick=function(){var tab=button.dataset.editorTab;if(isEditorTabLocked(tab)){requireProtectedAccess();return;}state.editorTab=tab;renderEditor();};});
    editor.querySelectorAll('[data-field]').forEach(function(input){input.oninput=function(){f[input.dataset.field]=input.value;};});
    editor.querySelectorAll('[data-feature]').forEach(function(input){input.onchange=function(){f.features[input.dataset.feature]=input.checked;};});
    editor.querySelectorAll('[data-step]').forEach(function(btn){btn.onclick=function(){var k=btn.dataset.resource,delta=Number(btn.dataset.step),next=Math.max(0,Math.min(5,Number(f.resources[k])+delta));if(delta>0&&total(f)>=5){setMessage(tr('maxFive'),'error');return;}f.resources[k]=next;renderEditor();};});
    editor.querySelectorAll('[data-zombie]').forEach(function(input){input.onchange=function(){var k=input.dataset.zombie;f.zombie[k]=k==='multiplier'?input.value:Number(input.value);};});
    editor.querySelectorAll('[data-shop]').forEach(function(input){input.onchange=function(){var shop=input.dataset.shop,id=Number(input.dataset.item),list=f.shops[shop]||[];f.shops[shop]=input.checked?Array.from(new Set(list.concat([id]))):list.filter(function(x){return Number(x)!==id;});};});
    var showPass=document.getElementById('showPass');if(showPass){showPass.onclick=function(){var p=document.getElementById('password');p.type=p.type==='password'?'text':'password';};}
  }
  function editorTabsHtml(){var tabs=[['identity','◆',tr('castleSettings')],['functions','⚙',tr('functions')],['gathering','⛏',tr('gather')],['zombie','☣',tr('zombie')],['arena','🏟',tr('arenaStore')],['vip','👑',tr('vipStore')]];return '<nav class="editor-tabs" aria-label="'+esc(tr('castleSettings'))+'">'+tabs.map(function(tab){var locked=isEditorTabLocked(tab[0]);return '<button class="editor-tab '+(state.editorTab===tab[0]?'active ':'')+(locked?'locked':'')+'" type="button" data-editor-tab="'+tab[0]+'" aria-selected="'+String(state.editorTab===tab[0])+'" aria-disabled="'+String(locked)+'">'+(locked?'🔒':tab[1])+'<span>'+esc(tab[2])+'</span></button>';}).join('')+'</nav>';}
  function editorTabHtml(f){if(!isEditorTabAllowed(state.editorTab)){return '';}if(state.editorTab==='identity'){return identityHtml(f);}if(state.editorTab==='gathering'){return resourcesHtml(f);}return '';}
  function protectedPanelHtml(){return '<section class="section-card protected-panel"><span>🔒</span><h3>'+esc(tr('protectedSection'))+'</h3><p>'+esc(tr('notAuthorized'))+'</p></section>';}
  function identityHtml(f){var credentials=state.adminEdit?'':'<label class="form-row"><span class="label">'+esc(tr('email'))+'</span><input class="field" data-field="login" type="email" value="'+esc(f.login)+'"></label><label class="form-row full"><span class="label">'+esc(tr('password'))+'</span><span class="password-wrap"><input id="password" class="field" data-field="password" type="password" value="" placeholder="'+esc(tr('passwordHint'))+'"><button id="showPass" class="small-btn" type="button">👁</button></span></label>';return '<section class="section-card"><h3 class="section-title"><span>◆</span>'+esc(tr('identity'))+'</h3><div class="form-grid"><label class="form-row"><span class="label">'+esc(tr('nickname'))+'</span><input class="field" data-field="castle_name" value="'+esc(f.castle_name)+'"></label>'+credentials+'</div></section>';}
  function featureToggleHtml(key,label,f){return '<label class="context-feature"><span><small>'+esc(tr('functions'))+'</small><b>'+esc(label)+'</b></span>'+fireSwitch('type="checkbox" data-feature="'+key+'" aria-label="'+esc(label)+'"',!!f.features[key])+'</label>';}
  function resourcesHtml(f){return featureToggleHtml('gathering',featureName('gathering'),f)+'<section class="section-card"><h3 class="section-title"><span>⛏</span>'+esc(tr('gather'))+'</h3><div class="resource-grid">'+['food','wood','steel','oil'].map(function(k){return '<div class="resource"><b>'+esc(tr(k))+'</b><button class="step" data-resource="'+k+'" data-step="-1">−</button><span class="count">'+Number(f.resources[k])+'</span><button class="step" data-resource="'+k+'" data-step="1">+</button></div>';}).join('')+'</div><div class="total"><span>'+esc(tr('total'))+'</span><strong>'+total(f)+' / 5</strong></div></section>';}
  function zombieHtml(f){var options=['auto','10','5','2','1'];return featureToggleHtml('zombie',featureName('zombie'),f)+'<section class="section-card"><h3 class="section-title"><span>☣</span>'+esc(tr('zombie'))+'</h3><div class="form-grid"><label class="form-row"><span class="label">'+esc(tr('maxLevel'))+'</span><input class="field" type="number" min="1" max="100" data-zombie="max_level" value="'+Number(f.zombie.max_level)+'"></label><label class="form-row"><span class="label">'+esc(tr('minLevel'))+'</span><input class="field" type="number" min="1" max="100" data-zombie="min_level" value="'+Number(f.zombie.min_level)+'"></label><label class="form-row full"><span class="label">'+esc(tr('multiplier'))+'</span><select class="select" data-zombie="multiplier">'+options.map(function(x){return '<option value="'+x+'" '+(String(f.zombie.multiplier)===x?'selected':'')+'>'+(x==='auto'?esc(tr('auto')):(x==='1'?esc(tr('normal')):'×'+x))+'</option>';}).join('')+'</select></label></div></section>';}
  function shopHtml(name,title,f){var feature=name+'_store';return featureToggleHtml(feature,featureName(feature),f)+'<section class="section-card"><h3 class="section-title"><span>🛒</span>'+esc(title)+'</h3><div class="note">'+esc(tr('shopSafety'))+'</div>'+shopList(name,title,f)+'</section>';}
  function shopList(name,title,f){var selected=(f.shops[name]||[]).map(Number);var items=state.catalog[name]||[];return '<h4>'+esc(title)+'</h4><div class="shop-list">'+items.map(function(item){var unlock=item.unlock_level?(name==='vip'?tr('vip')+' ': 'Rank ')+item.unlock_level:'';return '<label class="shop-item">'+fireSwitch('type="checkbox" data-shop="'+name+'" data-item="'+item.item_id+'"',selected.includes(Number(item.item_id)))+'<span><div class="shop-item-name">'+esc(itemName(item))+'</div><div class="shop-item-meta">ID '+item.item_id+' · '+esc(tr('qty'))+' '+item.quantity+(unlock?' · '+esc(unlock):'')+'</div></span><span class="price">'+item.price+' '+esc(name==='arena'?tr('points'):tr(['','gems','oil','food','wood','steel'][item.currency_subtype]||''))+'</span></label>';}).join('')+'</div>';}

  function validate() {
    for(var i=0;i<state.farms.length;i++){var f=state.farms[i];if((!state.adminEdit&&!f.login)||total(f)>5||Number(f.zombie.min_level)<1||Number(f.zombie.max_level)>100||Number(f.zombie.min_level)>Number(f.zombie.max_level)){return false;}}
    return true;
  }
  function base64Url(bytes){
    var binary='',size=0x8000;
    for(var offset=0;offset<bytes.length;offset+=size){binary+=String.fromCharCode.apply(null,bytes.subarray(offset,offset+size));}
    return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
  }
  async function compressedSaveRequest(request){
    var raw=JSON.stringify(request),source=new TextEncoder().encode(raw);
    if(source.length<=4096){return raw;}
    if(typeof CompressionStream!=='function'){throw new Error('compression unavailable');}
    var stream=new Blob([source]).stream().pipeThrough(new CompressionStream('deflate'));
    var compressed=new Uint8Array(await new Response(stream).arrayBuffer());
    var wire=JSON.stringify({z:1,d:base64Url(compressed)});
    if(new TextEncoder().encode(wire).length>4096){throw new Error('save request too large');}
    return wire;
  }
  function sendFarmEnabled(farm,enabled){
    if(!payload||!hasTelegramScope()){setMessage(tr('notAuthorized'),'error');return false;}
    if(!tg){setMessage(tr('openTelegram'),'error');return false;}
    try{tg.sendData(JSON.stringify(addAdminScope({action:'set_farm_enabled',language:state.lang,kingdom_id:state.kingdom,owner_telegram_id:state.owner,farm_id:farm.id,enabled:!!enabled})));setMessage(tr('pendingConfirmation'),'success');return true;}
    catch(_){setMessage(tr('invalid'),'error');return false;}
  }
  function hasTelegramScope(){return state.owner>0&&state.kingdom>0;}
  function addAdminScope(request){if(state.adminEdit){request.a=1;request.x=state.adminFarmId;}return request;}
  function confirmLanguage(){
    setMessage('','');
    if(!payload||!hasTelegramScope()){setMessage(tr('notAuthorized'),'error');return;}
    if(!tg){setMessage(tr('openTelegram'),'error');return;}
    saveBtn.disabled=true;
    try{tg.sendData(JSON.stringify({action:'set_language',language:state.lang,kingdom_id:state.kingdom,owner_telegram_id:state.owner}));}
    catch(_){setMessage(tr('invalid'),'error');saveBtn.disabled=false;}
  }
  async function saveAll() {
    setMessage('','');if(!payload||!validate()){setMessage(tr('invalid'),'error');return;}if(!tg){setMessage(tr('openTelegram'),'error');return;}
    saveBtn.disabled=true;saveBtn.textContent=tr('saving');
    var orders=state.farms.map(function(f){return {farm_id:f.id,settings:{castle_name:f.castle_name,login:f.login,password:f.password,on_off:f.on_off},resources:f.resources,operation:'gather',zombie:f.zombie,features:f.features,shops:f.shops};});
    try { var request=addAdminScope({action:'save_settings',language:state.lang,kingdom_id:state.kingdom,owner_telegram_id:state.owner,orders:orders});tg.sendData(await compressedSaveRequest(request));setMessage(tr('pendingConfirmation'),'success'); }
    catch(_){setMessage(tr('invalid'),'error');saveBtn.disabled=false;saveBtn.textContent='💾 '+tr('save');}
  }

  backBtn.onclick=function(){renderHome();};
  document.getElementById('languageBtn').onclick=renderLanguage;
  saveBtn.onclick=async function(){if(state.screen==='language'){confirmLanguage();return;}await saveAll();};
  if (!payload) { state.lang='en'; renderHome(); setMessage(tr('openTelegram'),'error'); }
  else if(state.adminEdit&&state.farms.length===1){state.current=state.farms[0];renderEditor();}
  else { renderHome(); }
})();
