(function () {
  'use strict';

  var tg = window.Telegram && window.Telegram.WebApp ? window.Telegram.WebApp : null;
  if (tg) { try { tg.ready(); tg.expand(); tg.setHeaderColor('#100806'); tg.setBackgroundColor('#0c0706'); } catch (_) {} }

  var LANGS = [
    ['ar','🇸🇦','العربية'],['en','🇬🇧','English'],['fr','🇫🇷','Français'],['de','🇩🇪','Deutsch'],
    ['it','🇮🇹','Italiano'],['es','🇪🇸','Español'],['pt','🇵🇹','Português'],['ru','🇷🇺','Русский']
  ];
  var EN = {
    eyebrow:'CASTLE COMMAND',title:'Doomsday Command',subtitle:'Manage every castle from one control center.',telegram:'Telegram ID',search:'Search by nickname or castle ID',copy:'Copy settings',cancel:'Cancel',apply:'Apply settings',chooseSource:'Choose the source castle.',chooseTargets:'Select one or more target castles.',copied:'Settings copied to the selected castles.',noFarms:'No castles are linked to this Telegram account.',on:'ONLINE',off:'STOPPED',save:'Save all settings',saving:'Saving…',saved:'Settings sent to the bot.',openTelegram:'Open this page from the Telegram bot.',invalid:'Castle data is invalid. Reopen the page from the bot.',back:'Back',identity:'Castle identity',nickname:'Castle nickname',email:'IGG email',password:'New password',passwordHint:'Leave blank to keep the saved password',functions:'Automation functions',gather:'Resource gathering',food:'Food',wood:'Wood',steel:'Steel',oil:'Oil',total:'Total legions',maxFive:'The total cannot exceed 5 legions.',zombie:'Rebel / zombie settings',maxLevel:'Maximum level',minLevel:'Minimum level',multiplier:'Multiplier',auto:'Automatic: ×10, ×5, ×2, then normal',normal:'Normal',shops:'Stores',arenaStore:'Arena Store',vipStore:'VIP Store — resources only',shopSafety:'The bot buys only live selected items. Gems and paid attempt purchases are permanently blocked.',points:'points',vip:'VIP',qty:'Qty',language:'Language',source:'Source',targets:'Targets',selectTarget:'Select target castles first.',transfer:'Transfer resources',transferTarget:'Receiving castle ID',transferHint:'Select the farms below, then enter the amount each selected farm should send.',selectedFarms:'Selected farms',enterAmounts:'Amount from each farm',sendTransfer:'Send resources',confirmTransfer:'Confirm transfer',close:'Close',transferInvalid:'Enter a valid target ID, select at least one farm, and enter a resource amount.',transferSent:'Transfer request sent. The bot will send the detailed report in Telegram.',perFarm:'The same amounts apply to every selected farm.'
  };
  var OV = {
    ar:{eyebrow:'قيادة القلاع',title:'قيادة دومزداي',subtitle:'تحكم في كل قلاعك من لوحة واحدة.',telegram:'معرّف تيليجرام',search:'ابحث باسم القلعة أو المعرّف',copy:'نسخ الإعدادات',cancel:'إلغاء',apply:'تطبيق الإعدادات',chooseSource:'اختر القلعة المصدر.',chooseTargets:'علّم على قلعة أو أكثر لتطبيق الإعدادات.',copied:'تم نسخ الإعدادات إلى القلاع المحددة.',noFarms:'لا توجد قلاع مرتبطة بحساب تيليجرام.',on:'شغالة',off:'متوقفة',save:'حفظ كل الإعدادات',saving:'جاري الحفظ…',saved:'تم إرسال الإعدادات إلى البوت.',openTelegram:'افتح الصفحة من زر البوت داخل تيليجرام.',invalid:'بيانات القلاع غير صالحة. افتح الصفحة من البوت من جديد.',back:'رجوع',identity:'بيانات القلعة',nickname:'اسم مختصر للقلعة',email:'بريد IGG',password:'كلمة مرور جديدة',passwordHint:'اتركها فارغة للاحتفاظ بالمحفوظة',functions:'دوال التشغيل',gather:'جمع الموارد',food:'الطعام',wood:'الخشب',steel:'الفولاذ',oil:'البترول',total:'إجمالي الفيالق',maxFive:'الإجمالي لا يزيد عن 5 فيالق.',zombie:'إعدادات المتمردين / الزومبي',maxLevel:'أقصى مستوى',minLevel:'أدنى مستوى',multiplier:'المضاعف',auto:'تلقائي: ×10 ثم ×5 ثم ×2 ثم عادي',normal:'عادي',shops:'المتاجر',arenaStore:'متجر الحلبة',vipStore:'متجر VIP — بالموارد فقط',shopSafety:'الشراء من العناصر المختارة والمتاحة حاليًا فقط. الجواهر وشراء محاولات إضافية ممنوعان نهائيًا.',points:'نقطة',vip:'VIP',qty:'الكمية',language:'اللغة',source:'المصدر',targets:'الأهداف',selectTarget:'اختر قلاعًا مستهدفة أولًا.',transfer:'نقل الموارد',transferTarget:'معرف القلعة المستلمة',transferHint:'علّم على المزارع بالأسفل، ثم اكتب الكمية التي سترسلها كل مزرعة محددة.',selectedFarms:'المزارع المحددة',enterAmounts:'الكمية من كل مزرعة',sendTransfer:'إرسال الموارد',confirmTransfer:'تأكيد الإرسال',close:'إغلاق',transferInvalid:'اكتب معرفًا صحيحًا، وحدد مزرعة واحدة على الأقل، واكتب كمية مورد.',transferSent:'تم إرسال الطلب. سيصلك التقرير التفصيلي في تيليجرام.',perFarm:'نفس الكميات ستُطبق على كل مزرعة محددة.'},
    fr:{eyebrow:'COMMANDE DES CHÂTEAUX',title:'Commande Doomsday',subtitle:'Gérez tous vos châteaux depuis un seul écran.',search:'Rechercher par surnom ou ID',copy:'Copier les réglages',cancel:'Annuler',apply:'Appliquer',chooseSource:'Choisissez le château source.',chooseTargets:'Sélectionnez les châteaux cibles.',copied:'Réglages copiés.',noFarms:'Aucun château lié.',on:'ACTIF',off:'ARRÊTÉ',save:'Enregistrer tous les réglages',saving:'Enregistrement…',saved:'Réglages envoyés au bot.',back:'Retour',identity:'Identité du château',nickname:'Surnom du château',email:'E-mail IGG',password:'Nouveau mot de passe',passwordHint:'Laisser vide pour conserver le mot de passe',functions:'Fonctions automatiques',gather:'Collecte de ressources',food:'Nourriture',wood:'Bois',steel:'Acier',oil:'Pétrole',total:'Total des légions',maxFive:'Maximum 5 légions.',zombie:'Rebelles / zombies',maxLevel:'Niveau maximal',minLevel:'Niveau minimal',multiplier:'Multiplicateur',auto:'Auto : ×10, ×5, ×2, puis normal',normal:'Normal',shops:'Boutiques',arenaStore:'Boutique de l’arène',vipStore:'Boutique VIP — ressources uniquement',shopSafety:'Uniquement les objets sélectionnés disponibles. Gemmes et tentatives payantes bloquées.',points:'points',qty:'Qté',language:'Langue',selectTarget:'Sélectionnez des châteaux cibles.'},
    de:{eyebrow:'BURGEN-KOMMANDO',title:'Doomsday Kommando',subtitle:'Alle Burgen in einer Zentrale verwalten.',search:'Nach Name oder Burg-ID suchen',copy:'Einstellungen kopieren',cancel:'Abbrechen',apply:'Anwenden',chooseSource:'Quellburg wählen.',chooseTargets:'Zielburgen auswählen.',copied:'Einstellungen kopiert.',noFarms:'Keine Burgen verknüpft.',on:'AKTIV',off:'AUS',save:'Alle Einstellungen speichern',saving:'Speichern…',saved:'Einstellungen an den Bot gesendet.',back:'Zurück',identity:'Burgdaten',nickname:'Burgname',email:'IGG-E-Mail',password:'Neues Passwort',passwordHint:'Leer lassen, um das gespeicherte Passwort zu behalten',functions:'Automatisierungen',gather:'Ressourcen sammeln',food:'Nahrung',wood:'Holz',steel:'Stahl',oil:'Öl',total:'Legionen gesamt',maxFive:'Höchstens 5 Legionen.',zombie:'Rebellen / Zombies',maxLevel:'Maximale Stufe',minLevel:'Minimale Stufe',multiplier:'Multiplikator',auto:'Auto: ×10, ×5, ×2, dann normal',normal:'Normal',shops:'Läden',arenaStore:'Arena-Laden',vipStore:'VIP-Laden — nur Ressourcen',shopSafety:'Nur ausgewählte verfügbare Artikel. Edelsteine und bezahlte Versuche sind gesperrt.',points:'Punkte',qty:'Menge',language:'Sprache',selectTarget:'Zielburgen auswählen.'},
    it:{eyebrow:'COMANDO CASTELLI',title:'Comando Doomsday',subtitle:'Gestisci tutti i castelli da un solo pannello.',search:'Cerca per nome o ID',copy:'Copia impostazioni',cancel:'Annulla',apply:'Applica',chooseSource:'Scegli il castello sorgente.',chooseTargets:'Seleziona i castelli di destinazione.',copied:'Impostazioni copiate.',noFarms:'Nessun castello collegato.',on:'ATTIVO',off:'FERMO',save:'Salva tutte le impostazioni',saving:'Salvataggio…',saved:'Impostazioni inviate al bot.',back:'Indietro',identity:'Identità del castello',nickname:'Nome del castello',email:'E-mail IGG',password:'Nuova password',passwordHint:'Lascia vuoto per mantenere la password salvata',functions:'Funzioni automatiche',gather:'Raccolta risorse',food:'Cibo',wood:'Legno',steel:'Acciaio',oil:'Petrolio',total:'Legioni totali',maxFive:'Massimo 5 legioni.',zombie:'Ribelli / zombie',maxLevel:'Livello massimo',minLevel:'Livello minimo',multiplier:'Moltiplicatore',auto:'Auto: ×10, ×5, ×2, poi normale',normal:'Normale',shops:'Negozi',arenaStore:'Negozio Arena',vipStore:'Negozio VIP — solo risorse',shopSafety:'Solo oggetti selezionati e disponibili. Gemme e tentativi a pagamento sono bloccati.',points:'punti',qty:'Qtà',language:'Lingua',selectTarget:'Seleziona i castelli di destinazione.'},
    es:{eyebrow:'MANDO DE CASTILLOS',title:'Mando Doomsday',subtitle:'Gestiona todos tus castillos desde un panel.',search:'Buscar por nombre o ID',copy:'Copiar ajustes',cancel:'Cancelar',apply:'Aplicar',chooseSource:'Elige el castillo de origen.',chooseTargets:'Selecciona los castillos de destino.',copied:'Ajustes copiados.',noFarms:'No hay castillos vinculados.',on:'ACTIVO',off:'DETENIDO',save:'Guardar todos los ajustes',saving:'Guardando…',saved:'Ajustes enviados al bot.',back:'Volver',identity:'Identidad del castillo',nickname:'Nombre del castillo',email:'Correo IGG',password:'Nueva contraseña',passwordHint:'Déjalo vacío para conservar la guardada',functions:'Funciones automáticas',gather:'Recolección de recursos',food:'Comida',wood:'Madera',steel:'Acero',oil:'Petróleo',total:'Legiones totales',maxFive:'Máximo 5 legiones.',zombie:'Rebeldes / zombis',maxLevel:'Nivel máximo',minLevel:'Nivel mínimo',multiplier:'Multiplicador',auto:'Auto: ×10, ×5, ×2 y normal',normal:'Normal',shops:'Tiendas',arenaStore:'Tienda de Arena',vipStore:'Tienda VIP — solo recursos',shopSafety:'Solo artículos seleccionados y disponibles. Gemas e intentos de pago bloqueados.',points:'puntos',qty:'Cant.',language:'Idioma',selectTarget:'Selecciona castillos de destino.'},
    pt:{eyebrow:'COMANDO DOS CASTELOS',title:'Comando Doomsday',subtitle:'Gerencie todos os castelos em um painel.',search:'Buscar por nome ou ID',copy:'Copiar definições',cancel:'Cancelar',apply:'Aplicar',chooseSource:'Escolha o castelo de origem.',chooseTargets:'Selecione os castelos de destino.',copied:'Definições copiadas.',noFarms:'Nenhum castelo vinculado.',on:'ATIVO',off:'PARADO',save:'Salvar todas as definições',saving:'Salvando…',saved:'Definições enviadas ao bot.',back:'Voltar',identity:'Identidade do castelo',nickname:'Nome do castelo',email:'E-mail IGG',password:'Nova senha',passwordHint:'Deixe vazio para manter a senha salva',functions:'Funções automáticas',gather:'Coleta de recursos',food:'Comida',wood:'Madeira',steel:'Aço',oil:'Petróleo',total:'Total de legiões',maxFive:'Máximo de 5 legiões.',zombie:'Rebeldes / zumbis',maxLevel:'Nível máximo',minLevel:'Nível mínimo',multiplier:'Multiplicador',auto:'Auto: ×10, ×5, ×2 e normal',normal:'Normal',shops:'Lojas',arenaStore:'Loja da Arena',vipStore:'Loja VIP — apenas recursos',shopSafety:'Apenas itens selecionados e disponíveis. Gemas e tentativas pagos bloqueados.',points:'pontos',qty:'Qtd.',language:'Idioma',selectTarget:'Selecione castelos de destino.'},
    ru:{eyebrow:'УПРАВЛЕНИЕ ЗАМКАМИ',title:'Doomsday Командование',subtitle:'Все замки в одной панели.',search:'Поиск по имени или ID',copy:'Копировать настройки',cancel:'Отмена',apply:'Применить',chooseSource:'Выберите исходный замок.',chooseTargets:'Выберите целевые замки.',copied:'Настройки скопированы.',noFarms:'Нет привязанных замков.',on:'ВКЛ',off:'ВЫКЛ',save:'Сохранить все настройки',saving:'Сохранение…',saved:'Настройки отправлены боту.',back:'Назад',identity:'Данные замка',nickname:'Имя замка',email:'Почта IGG',password:'Новый пароль',passwordHint:'Оставьте пустым, чтобы сохранить пароль',functions:'Автоматические функции',gather:'Сбор ресурсов',food:'Еда',wood:'Дерево',steel:'Сталь',oil:'Нефть',total:'Всего легионов',maxFive:'Не более 5 легионов.',zombie:'Повстанцы / зомби',maxLevel:'Макс. уровень',minLevel:'Мин. уровень',multiplier:'Множитель',auto:'Авто: ×10, ×5, ×2, затем обычно',normal:'Обычно',shops:'Магазины',arenaStore:'Магазин арены',vipStore:'VIP-магазин — только ресурсы',shopSafety:'Только выбранные доступные товары. Самоцветы и платные попытки заблокированы.',points:'очки',qty:'Кол.',language:'Язык',selectTarget:'Выберите целевые замки.'}
  };
  var TRANSFER_OV = {
    fr:{transfer:'Transférer des ressources',transferTarget:'ID du château destinataire',transferHint:'Sélectionnez les fermes ci-dessous, puis la quantité envoyée par chaque ferme.',selectedFarms:'Fermes sélectionnées',enterAmounts:'Quantité par ferme',sendTransfer:'Envoyer',confirmTransfer:'Confirmer le transfert',close:'Fermer',transferInvalid:'Saisissez un ID valide, choisissez au moins une ferme et une quantité.',transferSent:'Demande envoyée. Le rapport détaillé arrivera dans Telegram.',perFarm:'Les mêmes quantités s’appliquent à chaque ferme sélectionnée.'},
    de:{transfer:'Ressourcen übertragen',transferTarget:'ID der empfangenden Burg',transferHint:'Farmen unten auswählen und die Menge je Farm eingeben.',selectedFarms:'Ausgewählte Farmen',enterAmounts:'Menge je Farm',sendTransfer:'Ressourcen senden',confirmTransfer:'Transfer bestätigen',close:'Schließen',transferInvalid:'Gültige Ziel-ID, mindestens eine Farm und eine Ressourcenmenge eingeben.',transferSent:'Transferanfrage gesendet. Der Detailbericht folgt in Telegram.',perFarm:'Dieselben Mengen gelten für jede ausgewählte Farm.'},
    it:{transfer:'Trasferisci risorse',transferTarget:'ID castello destinatario',transferHint:'Seleziona le fattorie e indica la quantità inviata da ciascuna.',selectedFarms:'Fattorie selezionate',enterAmounts:'Quantità per fattoria',sendTransfer:'Invia risorse',confirmTransfer:'Conferma trasferimento',close:'Chiudi',transferInvalid:'Inserisci un ID valido, scegli almeno una fattoria e una quantità.',transferSent:'Richiesta inviata. Il rapporto dettagliato arriverà su Telegram.',perFarm:'Le stesse quantità valgono per ogni fattoria selezionata.'},
    es:{transfer:'Transferir recursos',transferTarget:'ID del castillo receptor',transferHint:'Selecciona las granjas e indica la cantidad que enviará cada una.',selectedFarms:'Granjas seleccionadas',enterAmounts:'Cantidad por granja',sendTransfer:'Enviar recursos',confirmTransfer:'Confirmar transferencia',close:'Cerrar',transferInvalid:'Escribe un ID válido, elige al menos una granja y una cantidad.',transferSent:'Solicitud enviada. El informe detallado llegará por Telegram.',perFarm:'Las mismas cantidades se aplican a cada granja seleccionada.'},
    pt:{transfer:'Transferir recursos',transferTarget:'ID do castelo de destino',transferHint:'Selecione as fazendas e informe a quantidade enviada por cada uma.',selectedFarms:'Fazendas selecionadas',enterAmounts:'Quantidade por fazenda',sendTransfer:'Enviar recursos',confirmTransfer:'Confirmar transferência',close:'Fechar',transferInvalid:'Informe um ID válido, selecione ao menos uma fazenda e uma quantidade.',transferSent:'Solicitação enviada. O relatório detalhado chegará no Telegram.',perFarm:'As mesmas quantidades valem para cada fazenda selecionada.'},
    ru:{transfer:'Передать ресурсы',transferTarget:'ID замка-получателя',transferHint:'Выберите фермы ниже и укажите объём с каждой фермы.',selectedFarms:'Выбранные фермы',enterAmounts:'Количество с каждой фермы',sendTransfer:'Отправить ресурсы',confirmTransfer:'Подтвердить передачу',close:'Закрыть',transferInvalid:'Укажите верный ID, выберите ферму и объём ресурсов.',transferSent:'Запрос отправлен. Подробный отчёт придёт в Telegram.',perFarm:'Одинаковые объёмы применяются ко всем выбранным фермам.'}
  };

  var FEATURE_EN = {
    alliance_help:'Help alliance members',resource_challenge:'Select resource challenge',radar:'Radar Station',zombie:'Attack rebels / zombies',gathering:'Gather resources',daily_missions:'Daily Missions',training:'Train troops and speedup task',refinery:'Refine Common Ore',doomsday_express:'Doomsday Express',alliance_gifts:'Alliance gifts',mail_rewards:'Mail rewards',vip_daily_gift:'Daily VIP chest',alliance_technology:'Marked alliance technology',territory_rewards:'Territory rewards',event_rewards:'Free and event rewards',police_normal:'Police normal free search',police_advanced:'Police advanced free search',arena_of_doom:'Arena of Doom — free attempts',arena_store:'Buy from Arena Store',vip_store:'Buy from VIP Store'
  };
  var FEATURE_AR = {
    alliance_help:'مساعدة أعضاء التحالف',resource_challenge:'اختيار تحدي جمع الموارد',radar:'محطة الرادار',zombie:'مهاجمة المتمردين / الزومبي',gathering:'جمع الموارد',daily_missions:'المهام اليومية',training:'تجنيد الجنود ومهمة التسريع',refinery:'صقل الخام العادي',doomsday_express:'قطار دومزداي',alliance_gifts:'هدايا التحالف',mail_rewards:'جوائز البريد',vip_daily_gift:'صندوق VIP اليومي',alliance_technology:'تقنية التحالف المحددة',territory_rewards:'جوائز الإقليم',event_rewards:'الجوائز المجانية والأحداث',police_normal:'بحث مركز الشرطة العادي المجاني',police_advanced:'بحث مركز الشرطة المتقدم المجاني',arena_of_doom:'حلبة الهلاك — المحاولات المجانية',arena_store:'الشراء من متجر الحلبة',vip_store:'الشراء من متجر VIP'
  };
  var FEATURE_OTHER = {
    fr:{alliance_help:'Aider les membres de l’alliance',resource_challenge:'Choisir le défi de collecte',radar:'Station radar',zombie:'Attaquer les rebelles / zombies',gathering:'Collecter des ressources',daily_missions:'Missions quotidiennes',training:'Entraînement et accélération',refinery:'Raffiner le minerai commun',doomsday_express:'Doomsday Express',alliance_gifts:'Cadeaux d’alliance',mail_rewards:'Récompenses du courrier',vip_daily_gift:'Coffre VIP quotidien',alliance_technology:'Technologie d’alliance marquée',territory_rewards:'Récompenses de territoire',event_rewards:'Récompenses gratuites et événements',police_normal:'Recherche normale gratuite',police_advanced:'Recherche avancée gratuite',arena_of_doom:'Arène du destin — essais gratuits',arena_store:'Achats dans la boutique de l’arène',vip_store:'Achats dans la boutique VIP'},
    de:{alliance_help:'Allianzmitglieder helfen',resource_challenge:'Sammel-Herausforderung wählen',radar:'Radarstation',zombie:'Rebellen / Zombies angreifen',gathering:'Ressourcen sammeln',daily_missions:'Tägliche Missionen',training:'Truppen und Beschleunigung',refinery:'Gewöhnliches Erz raffinieren',doomsday_express:'Doomsday Express',alliance_gifts:'Allianzgeschenke',mail_rewards:'Post-Belohnungen',vip_daily_gift:'Tägliche VIP-Truhe',alliance_technology:'Markierte Allianztechnologie',territory_rewards:'Gebietsbelohnungen',event_rewards:'Gratis- und Eventbelohnungen',police_normal:'Normale Gratissuche',police_advanced:'Erweiterte Gratissuche',arena_of_doom:'Arena des Untergangs — gratis',arena_store:'Im Arena-Laden kaufen',vip_store:'Im VIP-Laden kaufen'},
    it:{alliance_help:'Aiuta i membri dell’alleanza',resource_challenge:'Scegli la sfida raccolta',radar:'Stazione radar',zombie:'Attacca ribelli / zombie',gathering:'Raccogli risorse',daily_missions:'Missioni giornaliere',training:'Addestramento e accelerazione',refinery:'Raffina minerale comune',doomsday_express:'Doomsday Express',alliance_gifts:'Regali dell’alleanza',mail_rewards:'Ricompense posta',vip_daily_gift:'Forziere VIP giornaliero',alliance_technology:'Tecnologia alleanza marcata',territory_rewards:'Ricompense territorio',event_rewards:'Ricompense gratis ed eventi',police_normal:'Ricerca normale gratuita',police_advanced:'Ricerca avanzata gratuita',arena_of_doom:'Arena del destino — tentativi gratis',arena_store:'Acquista nel negozio Arena',vip_store:'Acquista nel negozio VIP'},
    es:{alliance_help:'Ayudar a miembros de la alianza',resource_challenge:'Elegir desafío de recolección',radar:'Estación de radar',zombie:'Atacar rebeldes / zombis',gathering:'Recolectar recursos',daily_missions:'Misiones diarias',training:'Entrenamiento y aceleración',refinery:'Refinar mineral común',doomsday_express:'Doomsday Express',alliance_gifts:'Regalos de alianza',mail_rewards:'Recompensas del correo',vip_daily_gift:'Cofre VIP diario',alliance_technology:'Tecnología de alianza marcada',territory_rewards:'Recompensas de territorio',event_rewards:'Recompensas gratis y eventos',police_normal:'Búsqueda normal gratuita',police_advanced:'Búsqueda avanzada gratuita',arena_of_doom:'Arena del Juicio — intentos gratis',arena_store:'Comprar en Tienda de Arena',vip_store:'Comprar en Tienda VIP'},
    pt:{alliance_help:'Ajudar membros da aliança',resource_challenge:'Escolher desafio de coleta',radar:'Estação de radar',zombie:'Atacar rebeldes / zumbis',gathering:'Coletar recursos',daily_missions:'Missões diárias',training:'Treino e aceleração',refinery:'Refinar minério comum',doomsday_express:'Doomsday Express',alliance_gifts:'Presentes da aliança',mail_rewards:'Recompensas do correio',vip_daily_gift:'Baú VIP diário',alliance_technology:'Tecnologia marcada da aliança',territory_rewards:'Recompensas de território',event_rewards:'Recompensas grátis e eventos',police_normal:'Busca normal grátis',police_advanced:'Busca avançada grátis',arena_of_doom:'Arena do Juízo — tentativas grátis',arena_store:'Comprar na Loja da Arena',vip_store:'Comprar na Loja VIP'},
    ru:{alliance_help:'Помощь членам альянса',resource_challenge:'Выбрать испытание сбора',radar:'Радарная станция',zombie:'Атаковать повстанцев / зомби',gathering:'Собирать ресурсы',daily_missions:'Ежедневные задания',training:'Обучение и ускорение',refinery:'Переработать обычную руду',doomsday_express:'Doomsday Express',alliance_gifts:'Подарки альянса',mail_rewards:'Награды почты',vip_daily_gift:'Ежедневный VIP-сундук',alliance_technology:'Отмеченная технология альянса',territory_rewards:'Награды территории',event_rewards:'Бесплатные награды и события',police_normal:'Обычный бесплатный поиск',police_advanced:'Продвинутый бесплатный поиск',arena_of_doom:'Арена рока — бесплатные попытки',arena_store:'Покупки в магазине арены',vip_store:'Покупки в VIP-магазине'}
  };
  var FEATURE_GROUPS = [
    ['alliance_help','resource_challenge','radar','zombie','gathering','daily_missions','training','refinery','doomsday_express'],
    ['alliance_gifts','mail_rewards','vip_daily_gift','alliance_technology','territory_rewards','event_rewards'],
    ['police_normal','police_advanced','arena_of_doom','arena_store','vip_store']
  ];
  var DEFAULT_FEATURES = {};
  FEATURE_GROUPS.forEach(function (group) { group.forEach(function (key) { DEFAULT_FEATURES[key] = !['police_normal','police_advanced','arena_of_doom','arena_store','vip_store'].includes(key); }); });
  var STATIC_CATALOG = {
    arena:[
      [91030,'60m Training Speedup',1,21,750,0],[91031,'Advanced Search Map',1,21,9000,0],[91032,'Random Resource Pack III',1,21,15,0],[91033,'Intermediate Resource Pack',1,21,360,0],[91034,'Extermination Card',2,21,1000,0],[91035,'Battle Manual (5,000 EXP)',10,21,2500,0],[91036,'Defensive Fabric',300,21,4500,0],[91037,'Carbon Steel',10,21,1500,0],[91038,'Carbon Steel',60,21,9000,1001],[91039,'Shoes Fragment Choice Box',3,21,3000,0],[91040,'Pants Fragment Choice Box',3,21,3750,1002],[91041,'Honing Chip',1,21,2250,1003],[91042,'Shoes Fragment Choice Box',1,21,8500,1004],[91043,'Pants Fragment Choice Box',1,21,10600,1005],[91044,'Superb Shoes Fragment Choice Box',1,21,32000,1006],[91045,'Superb Pants Fragment Choice Box',1,21,40000,1007]
    ],
    vip:[
      [20010,'Stamina Recovery I',1,4,12000,1],[20011,'5m Speedup',1,3,4000,1],[20030,'Elite Hero Badge S',1,4,59000,3],[20032,'Beast Fragment Random Pod',1,3,200000,3],[20033,'Elite Beast Stim',1,4,375000,3],[20080,'Legendary Hero Badge S',1,3,450000,8],[20105,'High-Performance Motor Fragment',1,5,250000,10]
    ]
  };
  Object.keys(STATIC_CATALOG).forEach(function(shop){STATIC_CATALOG[shop]=STATIC_CATALOG[shop].map(function(x){return {item_id:x[0],name:x[1],quantity:x[2],currency_subtype:x[3],price:x[4],unlock_level:x[5]};});});
  var ITEM_IDS=[91030,91031,91032,91033,91034,91035,91036,91037,91038,91039,91040,91041,91042,91043,91044,91045,20010,20011,20030,20032,20033,20080,20105];
  var ITEM_NAMES={
    ar:['تسريع تدريب 60 دقيقة','خريطة بحث متقدمة','حزمة موارد عشوائية III','حزمة موارد متوسطة','بطاقة إبادة','دليل قتال (5000 خبرة)','نسيج دفاعي','فولاذ كربوني','فولاذ كربوني','صندوق اختيار أجزاء الحذاء','صندوق اختيار أجزاء البنطال','شريحة صقل','صندوق اختيار أجزاء الحذاء','صندوق اختيار أجزاء البنطال','صندوق أجزاء حذاء فائق','صندوق أجزاء بنطال فائق','استعادة طاقة I','تسريع 5 دقائق','شارة بطل نخبة S','حاوية أجزاء وحش عشوائية','منشط وحش نخبة','شارة بطل أسطوري S','جزء محرك عالي الأداء'],
    fr:['Accélération entraînement 60 min','Carte de recherche avancée','Pack de ressources aléatoire III','Pack de ressources intermédiaire','Carte d’extermination','Manuel de combat (5 000 EXP)','Tissu défensif','Acier au carbone','Acier au carbone','Coffre de fragments de chaussures','Coffre de fragments de pantalon','Puce de polissage','Coffre de fragments de chaussures','Coffre de fragments de pantalon','Coffre de chaussures superbe','Coffre de pantalon superbe','Récupération d’endurance I','Accélération 5 min','Insigne de héros élite S','Capsule aléatoire de fragments de bête','Stimulant de bête élite','Insigne de héros légendaire S','Fragment de moteur haute performance'],
    de:['Trainingsbeschleunigung 60 Min.','Erweiterte Suchkarte','Zufälliges Ressourcenpaket III','Mittleres Ressourcenpaket','Vernichtungskarte','Kampfhandbuch (5.000 EP)','Verteidigungsstoff','Kohlenstoffstahl','Kohlenstoffstahl','Schuhfragment-Auswahlkiste','Hosenfragment-Auswahlkiste','Polierchip','Schuhfragment-Auswahlkiste','Hosenfragment-Auswahlkiste','Erstklassige Schuhfragmentkiste','Erstklassige Hosenfragmentkiste','Ausdauerwiederherstellung I','Beschleunigung 5 Min.','Elite-Heldenabzeichen S','Zufällige Bestienfragment-Kapsel','Elite-Bestien-Stimulans','Legendäres Heldenabzeichen S','Hochleistungsmotor-Fragment'],
    it:['Accelerazione addestramento 60 min','Mappa ricerca avanzata','Pacco risorse casuale III','Pacco risorse intermedio','Carta sterminio','Manuale di battaglia (5.000 ESP)','Tessuto difensivo','Acciaio al carbonio','Acciaio al carbonio','Cassa scelta frammenti scarpe','Cassa scelta frammenti pantaloni','Chip di levigatura','Cassa scelta frammenti scarpe','Cassa scelta frammenti pantaloni','Cassa frammenti scarpe superba','Cassa frammenti pantaloni superba','Recupero resistenza I','Accelerazione 5 min','Distintivo eroe élite S','Capsula casuale frammenti bestia','Stimolante bestia élite','Distintivo eroe leggendario S','Frammento motore ad alte prestazioni'],
    es:['Aceleración de entrenamiento 60 min','Mapa de búsqueda avanzada','Paquete aleatorio de recursos III','Paquete intermedio de recursos','Tarjeta de exterminio','Manual de batalla (5.000 EXP)','Tejido defensivo','Acero al carbono','Acero al carbono','Caja de fragmentos de calzado','Caja de fragmentos de pantalón','Chip de pulido','Caja de fragmentos de calzado','Caja de fragmentos de pantalón','Caja superior de calzado','Caja superior de pantalón','Recuperación de aguante I','Aceleración 5 min','Insignia de héroe élite S','Cápsula aleatoria de fragmentos de bestia','Estimulante de bestia élite','Insignia de héroe legendario S','Fragmento de motor de alto rendimiento'],
    pt:['Aceleração de treino 60 min','Mapa de busca avançada','Pacote aleatório de recursos III','Pacote intermediário de recursos','Cartão de extermínio','Manual de batalha (5.000 EXP)','Tecido defensivo','Aço carbono','Aço carbono','Caixa de fragmentos de calçados','Caixa de fragmentos de calças','Chip de polimento','Caixa de fragmentos de calçados','Caixa de fragmentos de calças','Caixa superior de calçados','Caixa superior de calças','Recuperação de vigor I','Aceleração 5 min','Insígnia de herói elite S','Cápsula aleatória de fragmentos de fera','Estimulante de fera elite','Insígnia de herói lendário S','Fragmento de motor de alto desempenho'],
    ru:['Ускорение обучения 60 мин.','Продвинутая карта поиска','Случайный набор ресурсов III','Средний набор ресурсов','Карта истребления','Боевой справочник (5 000 опыта)','Защитная ткань','Углеродистая сталь','Углеродистая сталь','Ящик фрагментов обуви','Ящик фрагментов брюк','Чип шлифовки','Ящик фрагментов обуви','Ящик фрагментов брюк','Превосходный ящик обуви','Превосходный ящик брюк','Восстановление выносливости I','Ускорение 5 мин.','Знак элитного героя S','Случайная капсула фрагментов зверя','Стимулятор элитного зверя','Знак легендарного героя S','Фрагмент высокопроизводительного двигателя']
  };

  function decodeData() {
    try {
      var raw = new URLSearchParams(location.search).get('data');
      if (!raw) { return null; }
      raw = raw.replace(/-/g, '+').replace(/_/g, '/');
      while (raw.length % 4) { raw += '='; }
      return JSON.parse(decodeURIComponent(Array.prototype.map.call(atob(raw), function (c) { return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2); }).join('')));
    } catch (_) { return null; }
  }
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  var payload = decodeData();
  var state = {farms:[], catalog:STATIC_CATALOG, lang:'en', screen:'home', current:null, copyMode:null, source:null, targets:{}, transferTargets:{}, transferTarget:'', transferAmounts:{food:0,wood:0,steel:0,oil:0}, search:''};
  if (payload && (Array.isArray(payload.farms) || Array.isArray(payload.f))) {
    state.lang = (localStorage.getItem('doomsday-lang') || payload.language || payload.l || 'en').slice(0,2).toLowerCase();
    if (!LANGS.some(function (x) { return x[0] === state.lang; })) { state.lang = 'en'; }
    state.catalog = payload.shop_catalog || state.catalog;
    var rawFarms = payload.farms || payload.f.map(function(row){
      var featureKeys=FEATURE_GROUPS.reduce(function(a,b){return a.concat(b);},[]), features={};
      featureKeys.forEach(function(key,index){features[key]=!!(Number(row[6]) & Math.pow(2,index));});
      return {id:row[0],castle_name:row[1],login:row[2],on_off:row[3],resources:{food:row[4][0],wood:row[4][1],steel:row[4][2],oil:row[4][3]},zombie:{max_level:row[5][0],min_level:row[5][1],multiplier:String(row[5][2])},features:features,shops:{arena:row[7]||[],vip:row[8]||[]}};
    });
    state.farms = rawFarms.map(function (farm) {
      var features = Object.assign({}, DEFAULT_FEATURES, farm.features || {});
      return {
        id:String(farm.id), castle_name:String(farm.castle_name || ('farm-' + farm.id)), login:String(farm.login || ''), password:'', on_off:farm.on_off ? 1 : 0,
        resources:Object.assign({food:0,wood:0,steel:0,oil:0}, farm.resources || {}),
        zombie:Object.assign({max_level:40,min_level:35,multiplier:'auto'}, farm.zombie || {}),
        features:features, shops:Object.assign({arena:[],vip:[]}, farm.shops || {})
      };
    });
  }

  var home = document.getElementById('homeScreen'), editor = document.getElementById('editorScreen'), language = document.getElementById('languageScreen'), transferModal=document.getElementById('transferModal');
  var saveBtn = document.getElementById('saveBtn'), message = document.getElementById('message'), backBtn = document.getElementById('backBtn');
  function tr(key) { return (OV[state.lang] && OV[state.lang][key]) || (TRANSFER_OV[state.lang] && TRANSFER_OV[state.lang][key]) || EN[key] || key; }
  function featureName(key) { return state.lang === 'ar' ? FEATURE_AR[key] : ((FEATURE_OTHER[state.lang] && FEATURE_OTHER[state.lang][key]) || FEATURE_EN[key]); }
  function itemName(item) { var index=ITEM_IDS.indexOf(Number(item.item_id)), names=ITEM_NAMES[state.lang]; return index>=0&&names ? names[index] : item.name; }
  function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];}); }
  function setMessage(text, kind) { message.textContent = text || ''; message.className = kind || ''; }
  function total(farm) { return ['food','wood','steel','oil'].reduce(function (n,k) { return n + Number(farm.resources[k] || 0); },0); }
  function direction() { var rtl = state.lang === 'ar'; document.documentElement.dir = rtl ? 'rtl' : 'ltr'; document.documentElement.lang = state.lang; document.body.dataset.lang = state.lang; }

  function renderLanguage() {
    state.screen = 'language'; direction(); home.hidden = editor.hidden = true; language.hidden = false; backBtn.hidden = false; saveBtn.parentElement.hidden = true;
    language.innerHTML = '<h2 class="section-title"><span>🌐</span>'+esc(tr('language'))+'</h2><div class="languages">'+LANGS.map(function(x){return '<button class="language" data-lang="'+x[0]+'">'+x[1]+' '+esc(x[2])+'</button>';}).join('')+'</div>';
    language.querySelectorAll('[data-lang]').forEach(function(btn){btn.onclick=function(){state.lang=btn.dataset.lang;localStorage.setItem('doomsday-lang',state.lang);renderHome();};});
  }

  function renderHome() {
    state.screen = 'home'; state.current = null; direction(); language.hidden = editor.hidden = true; home.hidden = false; backBtn.hidden = true; saveBtn.parentElement.hidden = false;
    document.getElementById('eyebrow').textContent = tr('eyebrow'); document.getElementById('title').textContent = tr('title'); saveBtn.textContent = '💾 ' + tr('save');
    var rows = state.farms.filter(function(f){var q=state.search.toLowerCase();return !q || f.id.toLowerCase().includes(q) || f.castle_name.toLowerCase().includes(q);});
    var transferCount=Object.keys(state.transferTargets).filter(function(id){return state.transferTargets[id];}).length;
    var helper = state.copyMode ? '<div class="copy-panel">'+esc(state.copyMode==='source'?tr('chooseSource'):tr('chooseTargets'))+(state.source?' <b>'+esc(tr('source'))+': '+esc(state.source.castle_name)+'</b>':'')+'</div>' : '';
    home.innerHTML = '<div class="hero"><h2>'+esc(tr('title'))+'</h2><p>'+esc(tr('subtitle'))+' · '+esc(tr('telegram'))+' '+esc(payload ? (payload.telegram_id || payload.t) : '—')+'</p></div>'+ 
      '<section class="transfer-panel"><div class="transfer-heading"><div><b>📦 '+esc(tr('transfer'))+'</b><p>'+esc(tr('transferHint'))+'</p></div><span class="transfer-count">'+esc(tr('selectedFarms'))+': '+transferCount+'</span></div><div class="transfer-bar"><input id="transferTarget" class="field" inputmode="numeric" autocomplete="off" value="'+esc(state.transferTarget)+'" placeholder="'+esc(tr('transferTarget'))+'"><button id="transferBtn" class="transfer-btn" type="button">'+esc(tr('sendTransfer'))+'</button></div></section>'+
      '<div class="toolbar"><input id="search" class="field" value="'+esc(state.search)+'" placeholder="'+esc(tr('search'))+'"><button id="copyBtn" class="small-btn '+(state.copyMode?'active':'')+'">'+esc(state.copyMode?tr('cancel'):tr('copy'))+'</button>'+(state.copyMode==='targets'?'<button id="applyBtn" class="small-btn">'+esc(tr('apply'))+'</button>':'')+'</div>'+helper+
      '<div class="castle-list">'+(rows.length?rows.map(castleCard).join(''):'<div class="empty">🏚️<br>'+esc(payload?tr('noFarms'):tr('openTelegram'))+'</div>')+'</div>';
    document.getElementById('transferTarget').oninput=function(){state.transferTarget=this.value.replace(/\D/g,'').slice(0,20);this.value=state.transferTarget;};
    document.getElementById('transferBtn').onclick=openTransferModal;
    document.getElementById('search').oninput=function(){
      state.search=this.value;
      var q=state.search.toLowerCase();
      home.querySelectorAll('[data-farm]').forEach(function(card){
        var farm=state.farms.find(function(f){return f.id===card.dataset.farm;});
        card.hidden=!!q && !farm.id.toLowerCase().includes(q) && !farm.castle_name.toLowerCase().includes(q);
      });
    };
    document.getElementById('copyBtn').onclick=function(){state.copyMode=state.copyMode?null:'source';state.source=null;state.targets={};renderHome();};
    var apply=document.getElementById('applyBtn'); if(apply){apply.onclick=applyCopy;}
    home.querySelectorAll('[data-farm]').forEach(function(card){card.onclick=function(e){var farm=state.farms.find(function(f){return f.id===card.dataset.farm;});if(e.target.matches('[data-transfer-pick]')){e.stopPropagation();state.transferTargets[farm.id]=e.target.checked;renderHome();return;}if(e.target.matches('input')){e.stopPropagation();}selectCastle(farm);};});
  }
  function castleCard(farm) {
    var checked = state.targets[farm.id] ? ' checked' : '';
    var transferChecked=state.transferTargets[farm.id]?' checked':'';
    var pick = state.copyMode==='targets' ? '<input class="pick" type="checkbox" aria-label="target"'+checked+'>' : (state.copyMode==='source'?'<input class="pick" type="radio" name="source">':'<input class="pick" data-transfer-pick type="checkbox" aria-label="'+esc(tr('transfer'))+'"'+transferChecked+'>');
    return '<article class="castle-card" data-farm="'+esc(farm.id)+'"><div class="castle-icon">🏰</div><div><div class="castle-name">'+esc(farm.castle_name)+'</div><div class="castle-id">ID '+esc(farm.id)+'</div></div><div>'+pick+'<div class="status '+(farm.on_off?'on':'off')+'">'+esc(farm.on_off?tr('on'):tr('off'))+'</div></div></article>';
  }
  function selectCastle(farm) {
    if (state.copyMode==='source') { state.source=farm;state.copyMode='targets';renderHome();return; }
    if (state.copyMode==='targets') { if(state.source&&farm.id===state.source.id){return;}state.targets[farm.id]=!state.targets[farm.id];renderHome();return; }
    state.current=farm;renderEditor();
  }
  function applyCopy() {
    var ids=Object.keys(state.targets).filter(function(id){return state.targets[id];}); if(!ids.length){setMessage(tr('selectTarget'),'error');return;}
    ids.forEach(function(id){var farm=state.farms.find(function(f){return f.id===id;});farm.on_off=state.source.on_off;farm.resources=clone(state.source.resources);farm.zombie=clone(state.source.zombie);farm.features=clone(state.source.features);farm.shops=clone(state.source.shops);});
    state.copyMode=null;state.targets={};setMessage(tr('copied'),'success');renderHome();
  }

  function selectedTransferFarms(){return Object.keys(state.transferTargets).filter(function(id){return state.transferTargets[id];});}
  function openTransferModal(){
    var ids=selectedTransferFarms(), target=String(state.transferTarget||'');
    if(!/^\d+$/.test(target)||target==='0'||!ids.length||ids.includes(target)){setMessage(tr('transferInvalid'),'error');return;}
    setMessage('','');
    transferModal.hidden=false;
    transferModal.innerHTML='<div class="modal-backdrop" data-close-transfer></div><section class="transfer-dialog" role="dialog" aria-modal="true"><div class="dialog-head"><div><h2>📦 '+esc(tr('enterAmounts'))+'</h2><p>'+esc(tr('perFarm'))+'</p></div><button id="closeTransfer" class="round-btn" type="button" aria-label="'+esc(tr('close'))+'">×</button></div><div class="transfer-summary"><span>'+esc(tr('transferTarget'))+'</span><b>ID '+esc(target)+'</b><span>'+esc(tr('selectedFarms'))+'</span><b>'+ids.length+'</b></div><div class="transfer-amounts">'+['food','wood','steel','oil'].map(function(k){return '<label><span>'+esc(tr(k))+'</span><input class="field" data-transfer-amount="'+k+'" type="number" inputmode="numeric" min="0" max="1000000000000" step="1" value="'+Number(state.transferAmounts[k]||0)+'"></label>';}).join('')+'</div><button id="confirmTransfer" class="gold-btn" type="button">'+esc(tr('confirmTransfer'))+'</button><div id="transferError" class="error transfer-error"></div></section>';
    document.getElementById('closeTransfer').onclick=closeTransferModal;
    transferModal.querySelector('[data-close-transfer]').onclick=closeTransferModal;
    transferModal.querySelectorAll('[data-transfer-amount]').forEach(function(input){input.oninput=function(){var value=Math.max(0,Math.min(1000000000000,Math.floor(Number(input.value)||0)));state.transferAmounts[input.dataset.transferAmount]=value;};});
    document.getElementById('confirmTransfer').onclick=confirmTransfer;
  }
  function closeTransferModal(){transferModal.hidden=true;transferModal.innerHTML='';}
  function requestId(){var bytes=new Uint32Array(2);if(window.crypto&&window.crypto.getRandomValues){window.crypto.getRandomValues(bytes);}else{bytes[0]=Math.floor(Math.random()*0xffffffff);bytes[1]=Math.floor(Math.random()*0xffffffff);}return 'tr_'+Date.now().toString(36)+'_'+bytes[0].toString(36)+bytes[1].toString(36);}
  function confirmTransfer(){
    var amounts={}, totalAmount=0;
    transferModal.querySelectorAll('[data-transfer-amount]').forEach(function(input){var value=Math.max(0,Math.min(1000000000000,Math.floor(Number(input.value)||0)));amounts[input.dataset.transferAmount]=value;totalAmount+=value;});
    var ids=selectedTransferFarms(), target=String(state.transferTarget||'');
    if(!totalAmount||!ids.length||!/^\d+$/.test(target)||ids.includes(target)){document.getElementById('transferError').textContent=tr('transferInvalid');return;}
    if(!tg){document.getElementById('transferError').textContent=tr('openTelegram');return;}
    var button=document.getElementById('confirmTransfer');button.disabled=true;
    try{tg.sendData(JSON.stringify({action:'transfer_resources',request_id:requestId(),language:state.lang,target_player_id:target,farm_ids:ids,resources:amounts}));setMessage(tr('transferSent'),'success');closeTransferModal();}
    catch(_){button.disabled=false;document.getElementById('transferError').textContent=tr('invalid');}
  }

  function renderEditor() {
    var f=state.current;state.screen='editor';direction();home.hidden=language.hidden=true;editor.hidden=false;backBtn.hidden=false;saveBtn.parentElement.hidden=false;saveBtn.textContent='💾 '+tr('save');
    document.getElementById('title').textContent=f.castle_name;
    editor.innerHTML='<div class="editor-head"><div><h2>🏰 '+esc(f.castle_name)+'</h2><div class="castle-id">ID '+esc(f.id)+'</div></div><button id="power" class="toggle '+(f.on_off?'on':'off')+'">'+esc(f.on_off?tr('on'):tr('off'))+'</button></div>'+
      identityHtml(f)+functionsHtml(f)+resourcesHtml(f)+zombieHtml(f)+shopsHtml(f);
    document.getElementById('power').onclick=function(){f.on_off=f.on_off?0:1;renderEditor();};
    editor.querySelectorAll('[data-field]').forEach(function(input){input.oninput=function(){f[input.dataset.field]=input.value;};});
    editor.querySelectorAll('[data-feature]').forEach(function(input){input.onchange=function(){f.features[input.dataset.feature]=input.checked;};});
    editor.querySelectorAll('[data-step]').forEach(function(btn){btn.onclick=function(){var k=btn.dataset.resource,delta=Number(btn.dataset.step),next=Math.max(0,Math.min(5,Number(f.resources[k])+delta));if(delta>0&&total(f)>=5){setMessage(tr('maxFive'),'error');return;}f.resources[k]=next;renderEditor();};});
    editor.querySelectorAll('[data-zombie]').forEach(function(input){input.onchange=function(){var k=input.dataset.zombie;f.zombie[k]=k==='multiplier'?input.value:Number(input.value);};});
    editor.querySelectorAll('[data-shop]').forEach(function(input){input.onchange=function(){var shop=input.dataset.shop,id=Number(input.dataset.item),list=f.shops[shop]||[];f.shops[shop]=input.checked?Array.from(new Set(list.concat([id]))):list.filter(function(x){return Number(x)!==id;});};});
    document.getElementById('showPass').onclick=function(){var p=document.getElementById('password');p.type=p.type==='password'?'text':'password';};
  }
  function identityHtml(f){return '<section class="section-card"><h3 class="section-title"><span>◆</span>'+esc(tr('identity'))+'</h3><div class="form-grid"><label class="form-row"><span class="label">'+esc(tr('nickname'))+'</span><input class="field" data-field="castle_name" value="'+esc(f.castle_name)+'"></label><label class="form-row"><span class="label">'+esc(tr('email'))+'</span><input class="field" data-field="login" type="email" value="'+esc(f.login)+'"></label><label class="form-row full"><span class="label">'+esc(tr('password'))+'</span><span class="password-wrap"><input id="password" class="field" data-field="password" type="password" value="" placeholder="'+esc(tr('passwordHint'))+'"><button id="showPass" class="small-btn" type="button">👁</button></span></label></div></section>';}
  function functionsHtml(f){var all=FEATURE_GROUPS.reduce(function(a,b){return a.concat(b);},[]);return '<section class="section-card"><h3 class="section-title"><span>⚙</span>'+esc(tr('functions'))+'</h3><div class="feature-grid">'+all.map(function(k){return '<label class="check-card"><input type="checkbox" data-feature="'+k+'" '+(f.features[k]?'checked':'')+'><span>'+esc(featureName(k))+'</span></label>';}).join('')+'</div></section>';}
  function resourcesHtml(f){return '<section class="section-card"><h3 class="section-title"><span>⛏</span>'+esc(tr('gather'))+'</h3><div class="resource-grid">'+['food','wood','steel','oil'].map(function(k){return '<div class="resource"><b>'+esc(tr(k))+'</b><button class="step" data-resource="'+k+'" data-step="-1">−</button><span class="count">'+Number(f.resources[k])+'</span><button class="step" data-resource="'+k+'" data-step="1">+</button></div>';}).join('')+'</div><div class="total"><span>'+esc(tr('total'))+'</span><strong>'+total(f)+' / 5</strong></div></section>';}
  function zombieHtml(f){var options=['auto','10','5','2','1'];return '<section class="section-card"><h3 class="section-title"><span>☣</span>'+esc(tr('zombie'))+'</h3><div class="form-grid"><label class="form-row"><span class="label">'+esc(tr('maxLevel'))+'</span><input class="field" type="number" min="1" max="100" data-zombie="max_level" value="'+Number(f.zombie.max_level)+'"></label><label class="form-row"><span class="label">'+esc(tr('minLevel'))+'</span><input class="field" type="number" min="1" max="100" data-zombie="min_level" value="'+Number(f.zombie.min_level)+'"></label><label class="form-row full"><span class="label">'+esc(tr('multiplier'))+'</span><select class="select" data-zombie="multiplier">'+options.map(function(x){return '<option value="'+x+'" '+(String(f.zombie.multiplier)===x?'selected':'')+'>'+(x==='auto'?esc(tr('auto')):(x==='1'?esc(tr('normal')):'×'+x))+'</option>';}).join('')+'</select></label></div></section>';}
  function shopsHtml(f){return '<section class="section-card"><h3 class="section-title"><span>🛒</span>'+esc(tr('shops'))+'</h3><div class="note">'+esc(tr('shopSafety'))+'</div>'+shopList('arena',tr('arenaStore'),f)+shopList('vip',tr('vipStore'),f)+'</section>';}
  function shopList(name,title,f){var selected=(f.shops[name]||[]).map(Number);var items=state.catalog[name]||[];return '<h4>'+esc(title)+'</h4><div class="shop-list">'+items.map(function(item){var unlock=item.unlock_level?(name==='vip'?tr('vip')+' ': 'Rank ')+item.unlock_level:'';return '<label class="shop-item"><input type="checkbox" data-shop="'+name+'" data-item="'+item.item_id+'" '+(selected.includes(Number(item.item_id))?'checked':'')+'><span><div class="shop-item-name">'+esc(itemName(item))+'</div><div class="shop-item-meta">ID '+item.item_id+' · '+esc(tr('qty'))+' '+item.quantity+(unlock?' · '+esc(unlock):'')+'</div></span><span class="price">'+item.price+' '+esc(name==='arena'?tr('points'):tr(['','gems','oil','food','wood','steel'][item.currency_subtype]||''))+'</span></label>';}).join('')+'</div>';}

  function validate() {
    for(var i=0;i<state.farms.length;i++){var f=state.farms[i];if(!f.login||total(f)>5||Number(f.zombie.min_level)<1||Number(f.zombie.max_level)>100||Number(f.zombie.min_level)>Number(f.zombie.max_level)){return false;}}
    return true;
  }
  function saveAll() {
    setMessage('','');if(!payload||!validate()){setMessage(tr('invalid'),'error');return;}if(!tg){setMessage(tr('openTelegram'),'error');return;}
    saveBtn.disabled=true;saveBtn.textContent=tr('saving');
    var orders=state.farms.map(function(f){return {farm_id:f.id,settings:{castle_name:f.castle_name,login:f.login,password:f.password,on_off:f.on_off},resources:f.resources,operation:'gather',zombie:f.zombie,features:f.features,shops:f.shops};});
    try { tg.sendData(JSON.stringify({action:'save_settings',language:state.lang,orders:orders}));setMessage(tr('saved'),'success'); }
    catch(_){setMessage(tr('invalid'),'error');saveBtn.disabled=false;saveBtn.textContent='💾 '+tr('save');}
  }

  backBtn.onclick=function(){if(state.screen==='language'){renderHome();}else{renderHome();}};
  document.getElementById('languageBtn').onclick=renderLanguage;
  saveBtn.onclick=saveAll;
  if (!payload) { state.lang='en'; renderHome(); setMessage(tr('openTelegram'),'error'); }
  else { renderHome(); }
})();
